package de.il.torsten.pony;

@SuppressWarnings("unused")
public enum LanguageCodes {
    AAR("Afar"),
    ABK("Abkhazian"),
    ACE("Achinese"),
    ACH("Acoli"),
    ADA("Adangme"),
    ADY("Adyghe; Adygei"),
    AFA("Afro-Asiatic (Other)"),
    AFH("Afrihili"),
    AFR("Afrikaans"),
    AIN("Ainu"),
    AKA("Akan"),
    AKK("Akkadian"),
    ALB("Albanian"),
    ALE("Aleut"),
    ALG("Algonquian languages"),
    ALT("Southern Altai"),
    AMH("Amharic"),
    ANG("English, Old (ca.450-1100)"),
    ANP("Angika"),
    APA("Apache languages"),
    ARA("Arabic"),
    ARC("Aramaic"),
    ARG("Aragonese"),
    ARM("Armenian"),
    ARN("Mapudungun; Mapuche"),
    ARP("Arapaho"),
    ART("Artificial (Other)"),
    ARW("Arawak"),
    ASM("Assamese"),
    AST("Asturian; Bable"),
    ATH("Athapascan languages"),
    AUS("Australian languages"),
    AVA("Avaric"),
    AVE("Avestan"),
    AWA("Awadhi"),
    AYM("Aymara"),
    AZE("Azerbaijani"),
    BAD("Banda languages"),
    BAI("Bamileke languages"),
    BAK("Bashkir"),
    BAL("Baluchi"),
    BAM("Bambara"),
    BAN("Balinese"),
    BAQ("Basque"),
    BAS("Basa"),
    BAT("Baltic (Other)"),
    BEJ("Beja"),
    BEL("Belarusian"),
    BEM("Bemba"),
    BEN("Bengali"),
    BER("Berber (Other)"),
    BHO("Bhojpuri"),
    BIH("Bihari"),
    BIK("Bikol"),
    BIN("Bini; Edo"),
    BIS("Bislama"),
    BLA("Siksika"),
    BNT("Bantu (Other)"),
    BOS("Bosnian"),
    BRA("Braj"),
    BRE("Breton"),
    BTK("Batak languages"),
    BUA("Buriat"),
    BUG("Buginese"),
    BUL("Bulgarian"),
    BUR("Burmese"),
    BYN("Blin; Bilin"),
    CAD("Caddo"),
    CAI("Central American Indian (Other)"),
    CAR("Galibi Carib"),
    CAT("Catalan; Valencian"),
    CAU("Caucasian (Other)"),
    CEB("Cebuano"),
    CEL("Celtic (Other)"),
    CHA("Chamorro"),
    CHB("Chibcha"),
    CHE("Chechen"),
    CHG("Chagatai"),
    CHI("Chinese"),
    CHK("Chuukese"),
    CHM("Mari"),
    CHN("Chinook jargon"),
    CHO("Choctaw"),
    CHP("Chipewyan"),
    CHR("Cherokee"),
    CHU("Church Slavic; Old Slavonic; Church Slavonic; Old Bulgarian; Old Church Slavonic"),
    CHV("Chuvash"),
    CHY("Cheyenne"),
    CMC("Chamic languages"),
    COP("Coptic"),
    COR("Cornish"),
    COS("Corsican"),
    CPE("Creoles and pidgins, English based (Other)"),
    CPF("Creoles and pidgins, French-based (Other)"),
    CPP("Creoles and pidgins, Portuguese-based (Other)"),
    CRE("Cree"),
    CRH("Crimean Tatar; Crimean Turkish"),
    CRP("Creoles and pidgins (Other)"),
    CSB("Kashubian"),
    CUS("Cushitic (Other)"),
    CZE("Czech"),
    DAK("Dakota"),
    DAN("Danish"),
    DAR("Dargwa"),
    DAY("Land Dayak languages"),
    DEL("Delaware"),
    DEN("Slave (Athapascan)"),
    DGR("Dogrib"),
    DIN("Dinka"),
    DIV("Divehi; Dhivehi; Maldivian"),
    DOI("Dogri"),
    DRA("Dravidian (Other)"),
    DSB("Lower Sorbian"),
    DUA("Duala"),
    DUM("Dutch, Middle (ca.1050-1350)"),
    DUT("Dutch; Flemish"),
    DYU("Dyula"),
    DZO("Dzongkha"),
    EFI("Efik"),
    EGY("Egyptian (Ancient)"),
    EKA("Ekajuk"),
    ELX("Elamite"),
    ENG("English"),
    ENM("English, Middle (1100-1500)"),
    EPO("Esperanto"),
    EST("Estonian"),
    EWE("Ewe"),
    EWO("Ewondo"),
    FAN("Fang"),
    FAO("Faroese"),
    FAT("Fanti"),
    FIJ("Fijian"),
    FIL("Filipino; Pilipino"),
    FIN("Finnish"),
    FIU("Finno-Ugrian (Other)"),
    FON("Fon"),
    FRE("French"),
    FRM("French, Middle (ca.1400-1600)"),
    FRO("French, Old (842-ca.1400)"),
    FRR("Northern Frisian"),
    FRS("Eastern Frisian"),
    FRY("Western Frisian"),
    FUL("Fulah"),
    FUR("Friulian"),
    GAA("Ga"),
    GAY("Gayo"),
    GBA("Gbaya"),
    GEM("Germanic (Other)"),
    GEO("Georgian"),
    GER("German"),
    GEZ("Geez"),
    GIL("Gilbertese"),
    GLA("Gaelic; Scottish Gaelic"),
    GLE("Irish"),
    GLG("Galician"),
    GLV("Manx"),
    GMH("German, Middle High (ca.1050-1500)"),
    GOH("German, Old High (ca.750-1050)"),
    GON("Gondi"),
    GOR("Gorontalo"),
    GOT("Gothic"),
    GRB("Grebo"),
    GRC("Greek, Ancient (to 1453)"),
    GRE("Greek, Modern (1453-)"),
    GRN("Guarani"),
    GSW("Swiss German; Alemannic"),
    GUJ("Gujarati"),
    GWI("Gwich'in"),
    HAI("Haida"),
    HAT("Haitian; Haitian Creole"),
    HAU("Hausa"),
    HAW("Hawaiian"),
    HEB("Hebrew"),
    HER("Herero"),
    HIL("Hiligaynon"),
    HIM("Himachali"),
    HIN("Hindi"),
    HIT("Hittite"),
    HMN("Hmong"),
    HMO("Hiri Motu"),
    HSB("Upper Sorbian"),
    HUN("Hungarian"),
    HUP("Hupa"),
    IBA("Iban"),
    IBO("Igbo"),
    ICE("Icelandic"),
    IDO("Ido"),
    III("Sichuan Yi"),
    IJO("Ijo languages"),
    IKU("Inuktitut"),
    ILE("Interlingue"),
    ILO("Iloko"),
    INA("Interlingua (International Auxiliary Language Association)"),
    INC("Indic (Other)"),
    IND("Indonesian"),
    INE("Indo-European (Other)"),
    INH("Ingush"),
    IPK("Inupiaq"),
    IRA("Iranian (Other)"),
    IRO("Iroquoian languages"),
    ITA("Italian"),
    JAV("Javanese"),
    JBO("Lojban"),
    JPN("Japanese"),
    JPR("Judeo-Persian"),
    JRB("Judeo-Arabic"),
    KAA("Kara-Kalpak"),
    KAB("Kabyle"),
    KAC("Kachin; Jingpho"),
    KAL("Kalaallisut; Greenlandic"),
    KAM("Kamba"),
    KAN("Kannada"),
    KAR("Karen languages"),
    KAS("Kashmiri"),
    KAU("Kanuri"),
    KAW("Kawi"),
    KAZ("Kazakh"),
    KBD("Kabardian"),
    KHA("Khasi"),
    KHI("Khoisan (Other)"),
    KHM("Central Khmer"),
    KHO("Khotanese"),
    KIK("Kikuyu; Gikuyu"),
    KIN("Kinyarwanda"),
    KIR("Kirghiz; Kyrgyz"),
    KMB("Kimbundu"),
    KOK("Konkani"),
    KOM("Komi"),
    KON("Kongo"),
    KOR("Korean"),
    KOS("Kosraean"),
    KPE("Kpelle"),
    KRC("Karachay-Balkar"),
    KRL("Karelian"),
    KRO("Kru languages"),
    KRU("Kurukh"),
    KUA("Kuanyama; Kwanyama"),
    KUM("Kumyk"),
    KUR("Kurdish"),
    KUT("Kutenai"),
    LAD("Ladino"),
    LAH("Lahnda"),
    LAM("Lamba"),
    LAO("Lao"),
    LAT("Latin"),
    LAV("Latvian"),
    LEZ("Lezghian"),
    LIM("Limburgan; Limburger; Limburgish"),
    LIN("Lingala"),
    LIT("Lithuanian"),
    LOL("Mongo"),
    LOZ("Lozi"),
    LTZ("Luxembourgish; Letzeburgesch"),
    LUA("Luba-Lulua"),
    LUB("Luba-Katanga"),
    LUG("Ganda"),
    LUI("Luiseno"),
    LUN("Lunda"),
    LUO("Luo (Kenya and Tanzania)"),
    LUS("Lushai"),
    MAC("Macedonian"),
    MAD("Madurese"),
    MAG("Magahi"),
    MAH("Marshallese"),
    MAI("Maithili"),
    MAK("Makasar"),
    MAL("Malayalam"),
    MAN("Mandingo"),
    MAO("Maori"),
    MAP("Austronesian (Other)"),
    MAR("Marathi"),
    MAS("Masai"),
    MAY("Malay"),
    MDF("Moksha"),
    MDR("Mandar"),
    MEN("Mende"),
    MGA("Irish, Middle (900-1200)"),
    MIC("Mi'kmaq; Micmac"),
    MIN("Minangkabau"),
    MIS("Miscellaneous languages"),
    MKH("Mon-Khmer (Other)"),
    MLG("Malagasy"),
    MLT("Maltese"),
    MNC("Manchu"),
    MNI("Manipuri"),
    MNO("Manobo languages"),
    MOH("Mohawk"),
    MOL("Moldavian"),
    MON("Mongolian"),
    MOS("Mossi"),
    MUL("Multiple languages"),
    MUN("Munda languages"),
    MUS("Creek"),
    MWL("Mirandese"),
    MWR("Marwari"),
    MYN("Mayan languages"),
    MYV("Erzya"),
    NAH("Nahuatl languages"),
    NAI("North American Indian"),
    NAP("Neapolitan"),
    NAU("Nauru"),
    NAV("Navajo; Navaho"),
    NBL("Ndebele, South; South Ndebele"),
    NDE("Ndebele, North; North Ndebele"),
    NDO("Ndonga"),
    NDS("Low German; Low Saxon; German, Low; Saxon, Low"),
    NEP("Nepali"),
    NEW("Nepal Bhasa; Newari"),
    NIA("Nias"),
    NIC("Niger-Kordofanian (Other)"),
    NIU("Niuean"),
    NNO("Norwegian Nynorsk; Nynorsk, Norwegian"),
    NOB("Bokmål, Norwegian; Norwegian Bokmål"),
    NOG("Nogai"),
    NON("Norse, Old"),
    NOR("Norwegian"),
    NQO("N'Ko"),
    NSO("Pedi; Sepedi; Northern Sotho"),
    NUB("Nubian languages"),
    NWC("Classical Newari; Old Newari; Classical Nepal Bhasa"),
    NYA("Chichewa; Chewa; Nyanja"),
    NYM("Nyamwezi"),
    NYN("Nyankole"),
    NYO("Nyoro"),
    NZI("Nzima"),
    OCI("Occitan (post 1500); Provençal"),
    OJI("Ojibwa"),
    ORI("Oriya"),
    ORM("Oromo"),
    OSA("Osage"),
    OSS("Ossetian; Ossetic"),
    OTA("Turkish, Ottoman (1500-1928)"),
    OTO("Otomian languages"),
    PAA("Papuan (Other)"),
    PAG("Pangasinan"),
    PAL("Pahlavi"),
    PAM("Pampanga"),
    PAN("Panjabi; Punjabi"),
    PAP("Papiamento"),
    PAU("Palauan"),
    PEO("Persian, Old (ca.600-400 B.C.)"),
    PER("Persian"),
    PHI("Philippine (Other)"),
    PHN("Phoenician"),
    PLI("Pali"),
    POL("Polish"),
    PON("Pohnpeian"),
    POR("Portuguese"),
    PRA("Prakrit languages"),
    PRO("Provençal, Old (to 1500)"),
    PUS("Pushto"),
    QUE("Quechua"),
    RAJ("Rajasthani"),
    RAP("Rapanui"),
    RAR("Rarotongan; Cook Islands Maori"),
    ROA("Romance (Other)"),
    ROH("Romansh"),
    ROM("Romany"),
    RUM("Romanian"),
    RUN("Rundi"),
    RUP("Aromanian; Arumanian; Macedo-Romanian"),
    RUS("Russian"),
    SAD("Sandawe"),
    SAG("Sango"),
    SAH("Yakut"),
    SAI("South American Indian (Other)"),
    SAL("Salishan languages"),
    SAM("Samaritan Aramaic"),
    SAN("Sanskrit"),
    SAS("Sasak"),
    SAT("Santali"),
    SCC("Serbian"),
    SCN("Sicilian"),
    SCO("Scots"),
    SCR("Croatian"),
    SEL("Selkup"),
    SEM("Semitic (Other)"),
    SGA("Irish, Old (to 900)"),
    SGN("Sign Languages"),
    SHN("Shan"),
    SID("Sidamo"),
    SIN("Sinhala; Sinhalese"),
    SIO("Siouan languages"),
    SIT("Sino-Tibetan (Other)"),
    SLA("Slavic (Other)"),
    SLO("Slovak"),
    SLV("Slovenian"),
    SMA("Southern Sami"),
    SME("Northern Sami"),
    SMI("Sami languages (Other)"),
    SMJ("Lule Sami"),
    SMN("Inari Sami"),
    SMO("Samoan"),
    SMS("Skolt Sami"),
    SNA("Shona"),
    SND("Sindhi"),
    SNK("Soninke"),
    SOG("Sogdian"),
    SOM("Somali"),
    SON("Songhai languages"),
    SOT("Sotho, Southern"),
    SPA("Spanish; Castilian"),
    SRD("Sardinian"),
    SRN("Sranan Tongo"),
    SRR("Serer"),
    SSA("Nilo-Saharan (Other)"),
    SSW("Swati"),
    SUK("Sukuma"),
    SUN("Sundanese"),
    SUS("Susu"),
    SUX("Sumerian"),
    SWA("Swahili"),
    SWE("Swedish"),
    SYR("Syriac"),
    TAH("Tahitian"),
    TAI("Tai (Other)"),
    TAM("Tamil"),
    TAT("Tatar"),
    TEL("Telugu"),
    TEM("Timne"),
    TER("Tereno"),
    TET("Tetum"),
    TGK("Tajik"),
    TGL("Tagalog"),
    THA("Thai"),
    TIB("Tibetan"),
    TIG("Tigre"),
    TIR("Tigrinya"),
    TIV("Tiv"),
    TKL("Tokelau"),
    TLH("Klingon; tlhIngan-Hol"),
    TLI("Tlingit"),
    TMH("Tamashek"),
    TOG("Tonga (Nyasa)"),
    TON("Tonga (Tonga Islands)"),
    TPI("Tok Pisin"),
    TSI("Tsimshian"),
    TSN("Tswana"),
    TSO("Tsonga"),
    TUK("Turkmen"),
    TUM("Tumbuka"),
    TUP("Tupi languages"),
    TUR("Turkish"),
    TUT("Altaic (Other)"),
    TVL("Tuvalu"),
    TWI("Twi"),
    TYV("Tuvinian"),
    UDM("Udmurt"),
    UGA("Ugaritic"),
    UIG("Uighur; Uyghur"),
    UKR("Ukrainian"),
    UMB("Umbundu"),
    UND("Undetermined"),
    URD("Urdu"),
    UZB("Uzbek"),
    VAI("Vai"),
    VEN("Venda"),
    VIE("Vietnamese"),
    VOL("Volapük"),
    VOT("Votic"),
    WAK("Wakashan languages"),
    WAL("Walamo"),
    WAR("Waray"),
    WAS("Washo"),
    WEL("Welsh"),
    WEN("Sorbian languages"),
    WLN("Walloon"),
    WOL("Wolof"),
    XAL("Kalmyk; Oirat"),
    XHO("Xhosa"),
    YAO("Yao"),
    YAP("Yapese"),
    YID("Yiddish"),
    YOR("Yoruba"),
    YPK("Yupik languages"),
    ZAP("Zapotec"),
    ZEN("Zenaga"),
    ZHA("Zhuang; Chuang"),
    ZND("Zande languages"),
    ZUL("Zulu"),
    ZUN("Zuni"),
    ZXX("No linguistic content"),
    ZZA("Zaza; Dimili; Dimli; Kirdki; Kirmanjki; Zazaki.");

    public final String code, name;

    LanguageCodes(String aName) {
        this.code = name().toLowerCase();
        this.name = aName;
    }

    public String getDefault() {
        return GER.code;
    }
}
