package de.il.torsten.pony;

public enum UnitType {
    UT_10("group"),
    UT_11("outfit"),
    UT_13("ration"),
    UT_14("shot"),
    UT_15("stick, military"),
    UT_20("twenty foot container"),
    UT_21("forty foot container"),
    UT_22("decilitre per gram"),
    UT_23("gram per cubic centimetre"),
    UT_24("theoretical pound"),
    UT_25("gram per square centimetre"),
    UT_27("theoretical ton"),
    UT_28("kilogram per square metre"),
    UT_33("kilopascal square metre per gram"),
    UT_34("kilopascal per millimetre"),
    UT_35("millilitre per square centimetre second"),
    UT_37("ounce per square foot"),
    UT_38("ounce per square foot per 0,01inch"),
    UT_40("millilitre per second"),
    UT_41("millilitre per minute"),
    UT_56("sitas"),
    UT_57("mesh"),
    UT_58("net kilogram"),
    UT_59("part per million"),
    UT_60("percent weight"),
    UT_61("part per billion (US)"),
    UT_74("millipascal"),
    UT_77("milli-inch"),
    UT_80("pound per square inch absolute"),
    UT_81("henry"),
    UT_85("foot pound-force"),
    UT_87("pound per cubic foot"),
    UT_89("poise"),
    UT_91("stokes"),
    UT_1I("fixed rate"),
    UT_2A("radian per second"),
    UT_2B("radian per second squared"),
    UT_2C("roentgen"),
    UT_2G("volt AC"),
    UT_2H("volt DC"),
    UT_2I("British thermal unit (international table) per hour"),
    UT_2J("cubic centimetre per second"),
    UT_2K("cubic foot per hour"),
    UT_2L("cubic foot per minute"),
    UT_2M("centimetre per second"),
    UT_2N("decibel"),
    UT_2P("kilobyte"),
    UT_2Q("kilobecquerel"),
    UT_2R("kilocurie"),
    UT_2U("megagram"),
    UT_2X("metre per minute"),
    UT_2Y("milliroentgen"),
    UT_2Z("millivolt"),
    UT_3B("megajoule"),
    UT_3C("manmonth"),
    UT_4C("centistokes"),
    UT_4G("microlitre"),
    UT_4H("micrometre (micron)"),
    UT_4K("milliampere"),
    UT_4L("megabyte"),
    UT_4M("milligram per hour"),
    UT_4N("megabecquerel"),
    UT_4O("microfarad"),
    UT_4P("newton per metre"),
    UT_4Q("ounce inch"),
    UT_4R("ounce foot"),
    UT_4T("picofarad"),
    UT_4U("pound per hour"),
    UT_4W("ton (US) per hour"),
    UT_4X("kilolitre per hour"),
    UT_5A("barrel (US) per minute"),
    UT_5B("batch"),
    UT_5E("MMSCF/day"),
    UT_5J("hydraulic horse power"),
    UT_A10("ampere square metre per joule second"),
    UT_A11("angstrom"),
    UT_A12("astronomical unit"),
    UT_A13("attojoule"),
    UT_A14("barn"),
    UT_A15("barn per electronvolt"),
    UT_A16("barn per steradian electronvolt"),
    UT_A17("barn per steradian"),
    UT_A18("becquerel per kilogram"),
    UT_A19("becquerel per cubic metre"),
    UT_A2("ampere per centimetre"),
    UT_A20("British thermal unit (international table) per second square foot degree Rankine"),
    UT_A21("British thermal unit (international table) per pound degree Rankine"),
    UT_A22("British thermal unit (international table) per second foot degree Rankine"),
    UT_A23("British thermal unit (international table) per hour square foot degree Rankine"),
    UT_A24("candela per square metre"),
    UT_A26("coulomb metre"),
    UT_A27("coulomb metre squared per volt"),
    UT_A28("coulomb per cubic centimetre"),
    UT_A29("coulomb per cubic metre"),
    UT_A3("ampere per millimetre"),
    UT_A30("coulomb per cubic millimetre"),
    UT_A31("coulomb per kilogram second"),
    UT_A32("coulomb per mole"),
    UT_A33("coulomb per square centimetre"),
    UT_A34("coulomb per square metre"),
    UT_A35("coulomb per square millimetre"),
    UT_A36("cubic centimetre per mole"),
    UT_A37("cubic decimetre per mole"),
    UT_A38("cubic metre per coulomb"),
    UT_A39("cubic metre per kilogram"),
    UT_A4("ampere per square centimetre"),
    UT_A40("cubic metre per mole"),
    UT_A41("ampere per square metre"),
    UT_A42("curie per kilogram"),
    UT_A43("deadweight tonnage"),
    UT_A44("decalitre"),
    UT_A45("decametre"),
    UT_A47("decitex"),
    UT_A48("degree Rankine"),
    UT_A49("denier"),
    UT_A5("ampere square metre"),
    UT_A53("electronvolt"),
    UT_A54("electronvolt per metre"),
    UT_A55("electronvolt square metre"),
    UT_A56("electronvolt square metre per kilogram"),
    UT_A59("8-part cloud cover"),
    UT_A6("ampere per square metre kelvin squared"),
    UT_A68("exajoule"),
    UT_A69("farad per metre"),
    UT_A7("ampere per square millimetre"),
    UT_A70("femtojoule"),
    UT_A71("femtometre"),
    UT_A73("foot per second squared"),
    UT_A74("foot pound-force per second"),
    UT_A75("freight ton"),
    UT_A76("gal"),
    UT_A8("ampere second"),
    UT_A84("gigacoulomb per cubic metre"),
    UT_A85("gigaelectronvolt"),
    UT_A86("gigahertz"),
    UT_A87("gigaohm"),
    UT_A88("gigaohm metre"),
    UT_A89("gigapascal"),
    UT_A9("rate"),
    UT_A90("gigawatt"),
    UT_A91("gon"),
    UT_A93("gram per cubic metre"),
    UT_A94("gram per mole"),
    UT_A95("gray"),
    UT_A96("gray per second"),
    UT_A97("hectopascal"),
    UT_A98("henry per metre"),
    UT_A99("bit"),
    UT_AA("ball"),
    UT_AB("bulk pack"),
    UT_ACR("acre"),
    UT_ACT("activity"),
    UT_AD("byte"),
    UT_AE("ampere per metre"),
    UT_AH("additional minute"),
    UT_AI("average minute per call"),
    UT_AK("fathom"),
    UT_AL("access line"),
    UT_AMH("ampere hour"),
    UT_AMP("ampere"),
    UT_ANN("year"),
    UT_APZ("troy ounce or apothecary ounce"),
    UT_AQ("anti-hemophilic factor (AHF) unit"),
    UT_AS("assortment"),
    UT_ASM("alcoholic strength by mass"),
    UT_ASU("alcoholic strength by volume"),
    UT_ATM("standard atmosphere"),
    UT_AWG("american wire gauge"),
    UT_AY("assembly"),
    UT_AZ("British thermal unit (international table) per pound"),
    UT_B1("barrel (US) per day"),
    UT_B10("bit per second"),
    UT_B11("joule per kilogram kelvin"),
    UT_B12("joule per metre"),
    UT_B13("joule per square metre"),
    UT_B14("joule per metre to the fourth power"),
    UT_B15("joule per mole"),
    UT_B16("joule per mole kelvin"),
    UT_B17("credit"),
    UT_B18("joule second"),
    UT_B19("digit"),
    UT_B20("joule square metre per kilogram"),
    UT_B21("kelvin per watt"),
    UT_B22("kiloampere"),
    UT_B23("kiloampere per square metre"),
    UT_B24("kiloampere per metre"),
    UT_B25("kilobecquerel per kilogram"),
    UT_B26("kilocoulomb"),
    UT_B27("kilocoulomb per cubic metre"),
    UT_B28("kilocoulomb per square metre"),
    UT_B29("kiloelectronvolt"),
    UT_B3("batting pound"),
    UT_B30("gibibit"),
    UT_B31("kilogram metre per second"),
    UT_B32("kilogram metre squared"),
    UT_B33("kilogram metre squared per second"),
    UT_B34("kilogram per cubic decimetre"),
    UT_B35("kilogram per litre"),
    UT_B4("barrel, imperial"),
    UT_B41("kilojoule per kelvin"),
    UT_B42("kilojoule per kilogram"),
    UT_B43("kilojoule per kilogram kelvin"),
    UT_B44("kilojoule per mole"),
    UT_B45("kilomole"),
    UT_B46("kilomole per cubic metre"),
    UT_B47("kilonewton"),
    UT_B48("kilonewton metre"),
    UT_B49("kiloohm"),
    UT_B50("kiloohm metre"),
    UT_B52("kilosecond"),
    UT_B53("kilosiemens"),
    UT_B54("kilosiemens per metre"),
    UT_B55("kilovolt per metre"),
    UT_B56("kiloweber per metre"),
    UT_B57("light year"),
    UT_B58("litre per mole"),
    UT_B59("lumen hour"),
    UT_B60("lumen per square metre"),
    UT_B61("lumen per watt"),
    UT_B62("lumen second"),
    UT_B63("lux hour"),
    UT_B64("lux second"),
    UT_B66("megaampere per square metre"),
    UT_B67("megabecquerel per kilogram"),
    UT_B68("gigabit"),
    UT_B69("megacoulomb per cubic metre"),
    UT_B7("cycle"),
    UT_B70("megacoulomb per square metre"),
    UT_B71("megaelectronvolt"),
    UT_B72("megagram per cubic metre"),
    UT_B73("meganewton"),
    UT_B74("meganewton metre"),
    UT_B75("megaohm"),
    UT_B76("megaohm metre"),
    UT_B77("megasiemens per metre"),
    UT_B78("megavolt"),
    UT_B79("megavolt per metre"),
    UT_B8("joule per cubic metre"),
    UT_B80("gigabit per second"),
    UT_B81("reciprocal metre squared reciprocal second"),
    UT_B82("inch per linear foot"),
    UT_B83("metre to the fourth power"),
    UT_B84("microampere"),
    UT_B85("microbar"),
    UT_B86("microcoulomb"),
    UT_B87("microcoulomb per cubic metre"),
    UT_B88("microcoulomb per square metre"),
    UT_B89("microfarad per metre"),
    UT_B90("microhenry"),
    UT_B91("microhenry per metre"),
    UT_B92("micronewton"),
    UT_B93("micronewton metre"),
    UT_B94("microohm"),
    UT_B95("microohm metre"),
    UT_B96("micropascal"),
    UT_B97("microradian"),
    UT_B98("microsecond"),
    UT_B99("microsiemens"),
    UT_BAR("bar [unit of pressure]"),
    UT_BB("base box"),
    UT_BFT("board foot"),
    UT_BHP("brake horse power"),
    UT_BIL("billion (EUR)"),
    UT_BLD("dry barrel (US)"),
    UT_BLL("barrel (US)"),
    UT_BP("hundred board foot"),
    UT_BPM("beats per minute"),
    UT_BQL("becquerel"),
    UT_BTU("British thermal unit (international table)"),
    UT_BUA("bushel (US)"),
    UT_BUI("bushel (UK)"),
    UT_C0("call"),
    UT_C10("millifarad"),
    UT_C11("milligal"),
    UT_C12("milligram per metre"),
    UT_C13("milligray"),
    UT_C14("millihenry"),
    UT_C15("millijoule"),
    UT_C16("millimetre per second"),
    UT_C17("millimetre squared per second"),
    UT_C18("millimole"),
    UT_C19("mole per kilogram"),
    UT_C20("millinewton"),
    UT_C21("kibibit"),
    UT_C22("millinewton per metre"),
    UT_C23("milliohm metre"),
    UT_C24("millipascal second"),
    UT_C25("milliradian"),
    UT_C26("millisecond"),
    UT_C27("millisiemens"),
    UT_C28("millisievert"),
    UT_C29("millitesla"),
    UT_C3("microvolt per metre"),
    UT_C30("millivolt per metre"),
    UT_C31("milliwatt"),
    UT_C32("milliwatt per square metre"),
    UT_C33("milliweber"),
    UT_C34("mole"),
    UT_C35("mole per cubic decimetre"),
    UT_C36("mole per cubic metre"),
    UT_C37("kilobit"),
    UT_C38("mole per litre"),
    UT_C39("nanoampere"),
    UT_C40("nanocoulomb"),
    UT_C41("nanofarad"),
    UT_C42("nanofarad per metre"),
    UT_C43("nanohenry"),
    UT_C44("nanohenry per metre"),
    UT_C45("nanometre"),
    UT_C46("nanoohm metre"),
    UT_C47("nanosecond"),
    UT_C48("nanotesla"),
    UT_C49("nanowatt"),
    UT_C50("neper"),
    UT_C51("neper per second"),
    UT_C52("picometre"),
    UT_C53("newton metre second"),
    UT_C54("newton metre squared per kilogram squared"),
    UT_C55("newton per square metre"),
    UT_C56("newton per square millimetre"),
    UT_C57("newton second"),
    UT_C58("newton second per metre"),
    UT_C59("octave"),
    UT_C60("ohm centimetre"),
    UT_C61("ohm metre"),
    UT_C62("one"),
    UT_C63("parsec"),
    UT_C64("pascal per kelvin"),
    UT_C65("pascal second"),
    UT_C66("pascal second per cubic metre"),
    UT_C67("pascal second per metre"),
    UT_C68("petajoule"),
    UT_C69("phon"),
    UT_C7("centipoise"),
    UT_C70("picoampere"),
    UT_C71("picocoulomb"),
    UT_C72("picofarad per metre"),
    UT_C73("picohenry"),
    UT_C74("kilobit per second"),
    UT_C75("picowatt"),
    UT_C76("picowatt per square metre"),
    UT_C78("pound-force"),
    UT_C79("kilovolt ampere hour"),
    UT_C8("millicoulomb per kilogram"),
    UT_C80("rad"),
    UT_C81("radian"),
    UT_C82("radian square metre per mole"),
    UT_C83("radian square metre per kilogram"),
    UT_C84("radian per metre"),
    UT_C85("reciprocal angstrom"),
    UT_C86("reciprocal cubic metre"),
    UT_C87("reciprocal cubic metre per second"),
    UT_C88("reciprocal electron volt per cubic metre"),
    UT_C89("reciprocal henry"),
    UT_C9("coil group"),
    UT_C90("reciprocal joule per cubic metre"),
    UT_C91("reciprocal kelvin or kelvin to the power minus one"),
    UT_C92("reciprocal metre"),
    UT_C93("reciprocal square metre"),
    UT_C94("reciprocal minute"),
    UT_C95("reciprocal mole"),
    UT_C96("reciprocal pascal or pascal to the power minus one"),
    UT_C97("reciprocal second"),
    UT_C99("reciprocal second per metre squared"),
    UT_CCT("carrying capacity in metric ton"),
    UT_CDL("candela"),
    UT_CEL("degree Celsius"),
    UT_CEN("hundred"),
    UT_CG("card"),
    UT_CGM("centigram"),
    UT_CKG("coulomb per kilogram"),
    UT_CLF("hundred leave"),
    UT_CLT("centilitre"),
    UT_CMK("square centimetre"),
    UT_CMQ("cubic centimetre"),
    UT_CMT("centimetre"),
    UT_CNP("hundred pack"),
    UT_CNT("cental (UK)"),
    UT_COU("coulomb"),
    UT_CTG("content gram"),
    UT_CTM("metric carat"),
    UT_CTN("content ton (metric)"),
    UT_CUR("curie"),
    UT_CWA("hundred pound (cwt) / hundred weight (US)"),
    UT_CWI("hundred weight (UK)"),
    UT_D03("kilowatt hour per hour"),
    UT_D04("lot  [unit of weight]"),
    UT_D1("reciprocal second per steradian"),
    UT_D10("siemens per metre"),
    UT_D11("mebibit"),
    UT_D12("siemens square metre per mole"),
    UT_D13("sievert"),
    UT_D15("sone"),
    UT_D16("square centimetre per erg"),
    UT_D17("square centimetre per steradian erg"),
    UT_D18("metre kelvin"),
    UT_D19("square metre kelvin per watt"),
    UT_D2("reciprocal second per steradian metre squared"),
    UT_D20("square metre per joule"),
    UT_D21("square metre per kilogram"),
    UT_D22("square metre per mole"),
    UT_D23("pen gram (protein)"),
    UT_D24("square metre per steradian"),
    UT_D25("square metre per steradian joule"),
    UT_D26("square metre per volt second"),
    UT_D27("steradian"),
    UT_D29("terahertz"),
    UT_D30("terajoule"),
    UT_D31("terawatt"),
    UT_D32("terawatt hour"),
    UT_D33("tesla"),
    UT_D34("tex"),
    UT_D36("megabit"),
    UT_D41("tonne per cubic metre"),
    UT_D42("tropical year"),
    UT_D43("unified atomic mass unit"),
    UT_D44("var"),
    UT_D45("volt squared per kelvin squared"),
    UT_D46("volt - ampere"),
    UT_D47("volt per centimetre"),
    UT_D48("volt per kelvin"),
    UT_D49("millivolt per kelvin"),
    UT_D5("kilogram per square centimetre"),
    UT_D50("volt per metre"),
    UT_D51("volt per millimetre"),
    UT_D52("watt per kelvin"),
    UT_D53("watt per metre kelvin"),
    UT_D54("watt per square metre"),
    UT_D55("watt per square metre kelvin"),
    UT_D56("watt per square metre kelvin to the fourth power"),
    UT_D57("watt per steradian"),
    UT_D58("watt per steradian square metre"),
    UT_D59("weber per metre"),
    UT_D6("roentgen per second"),
    UT_D60("weber per millimetre"),
    UT_D61("minute [unit of angle]"),
    UT_D62("second [unit of angle]"),
    UT_D63("book"),
    UT_D65("round"),
    UT_D68("number of words"),
    UT_D69("inch to the fourth power"),
    UT_D73("joule square metre"),
    UT_D74("kilogram per mole"),
    UT_D77("megacoulomb"),
    UT_D78("megajoule per second"),
    UT_D80("microwatt"),
    UT_D81("microtesla"),
    UT_D82("microvolt"),
    UT_D83("millinewton metre"),
    UT_D85("microwatt per square metre"),
    UT_D86("millicoulomb"),
    UT_D87("millimole per kilogram"),
    UT_D88("millicoulomb per cubic metre"),
    UT_D89("millicoulomb per square metre"),
    UT_D91("rem"),
    UT_D93("second per cubic metre"),
    UT_D94("second per cubic metre radian"),
    UT_D95("joule per gram"),
    UT_DAA("decare"),
    UT_DAD("ten day"),
    UT_DAY("day"),
    UT_DB("dry pound"),
    UT_DBM("Decibel-milliwatts"),
    UT_DBW("Decibel watt"),
    UT_DD("degree [unit of angle]"),
    UT_DEC("decade"),
    UT_DG("decigram"),
    UT_DJ("decagram"),
    UT_DLT("decilitre"),
    UT_DMA("cubic decametre"),
    UT_DMK("square decimetre"),
    UT_DMO("standard kilolitre"),
    UT_DMQ("cubic decimetre"),
    UT_DMT("decimetre"),
    UT_DN("decinewton metre"),
    UT_DPC("dozen piece"),
    UT_DPR("dozen pair"),
    UT_DPT("displacement tonnage"),
    UT_DRA("dram (US)"),
    UT_DRI("dram (UK)"),
    UT_DRL("dozen roll"),
    UT_DT("dry ton"),
    UT_DTN("decitonne"),
    UT_DWT("pennyweight"),
    UT_DZN("dozen"),
    UT_DZP("dozen pack"),
    UT_E01("newton per square centimetre"),
    UT_E07("megawatt hour per hour"),
    UT_E08("megawatt per hertz"),
    UT_E09("milliampere hour"),
    UT_E10("degree day"),
    UT_E12("mille"),
    UT_E14("kilocalorie (international table)"),
    UT_E15("kilocalorie (thermochemical) per hour"),
    UT_E16("million Btu(IT) per hour"),
    UT_E17("cubic foot per second"),
    UT_E18("tonne per hour"),
    UT_E19("ping"),
    UT_E20("megabit per second"),
    UT_E21("shares"),
    UT_E22("TEU"),
    UT_E23("tyre"),
    UT_E25("active unit"),
    UT_E27("dose"),
    UT_E28("air dry ton"),
    UT_E30("strand"),
    UT_E31("square metre per litre"),
    UT_E32("litre per hour"),
    UT_E33("foot per thousand"),
    UT_E34("gigabyte"),
    UT_E35("terabyte"),
    UT_E36("petabyte"),
    UT_E37("pixel"),
    UT_E38("megapixel"),
    UT_E39("dots per inch"),
    UT_E4("gross kilogram"),
    UT_E40("part per hundred thousand"),
    UT_E41("kilogram-force per square millimetre"),
    UT_E42("kilogram-force per square centimetre"),
    UT_E43("joule per square centimetre"),
    UT_E44("kilogram-force metre per square centimetre"),
    UT_E45("milliohm"),
    UT_E46("kilowatt hour per cubic metre"),
    UT_E47("kilowatt hour per kelvin"),
    UT_E48("service unit"),
    UT_E49("working day"),
    UT_E50("accounting unit"),
    UT_E51("job"),
    UT_E52("run foot"),
    UT_E53("test"),
    UT_E54("trip"),
    UT_E55("use"),
    UT_E56("well"),
    UT_E57("zone"),
    UT_E58("exabit per second"),
    UT_E59("exbibyte"),
    UT_E60("pebibyte"),
    UT_E61("tebibyte"),
    UT_E62("gibibyte"),
    UT_E63("mebibyte"),
    UT_E64("kibibyte"),
    UT_E65("exbibit per metre"),
    UT_E66("exbibit per square metre"),
    UT_E67("exbibit per cubic metre"),
    UT_E68("gigabyte per second"),
    UT_E69("gibibit per metre"),
    UT_E70("gibibit per square metre"),
    UT_E71("gibibit per cubic metre"),
    UT_E72("kibibit per metre"),
    UT_E73("kibibit per square metre"),
    UT_E74("kibibit per cubic metre"),
    UT_E75("mebibit per metre"),
    UT_E76("mebibit per square metre"),
    UT_E77("mebibit per cubic metre"),
    UT_E78("petabit"),
    UT_E79("petabit per second"),
    UT_E80("pebibit per metre"),
    UT_E81("pebibit per square metre"),
    UT_E82("pebibit per cubic metre"),
    UT_E83("terabit"),
    UT_E84("terabit per second"),
    UT_E85("tebibit per metre"),
    UT_E86("tebibit per cubic metre"),
    UT_E87("tebibit per square metre"),
    UT_E88("bit per metre"),
    UT_E89("bit per square metre"),
    UT_E90("reciprocal centimetre"),
    UT_E91("reciprocal day"),
    UT_E92("cubic decimetre per hour"),
    UT_E93("kilogram per hour"),
    UT_E94("kilomole per second"),
    UT_E95("mole per second"),
    UT_E96("degree per second"),
    UT_E97("millimetre per degree Celcius metre"),
    UT_E98("degree Celsius per kelvin"),
    UT_E99("hectopascal per bar"),
    UT_EA("each"),
    UT_EB("electronic mail box"),
    UT_EQ("equivalent gallon"),
    UT_F01("bit per cubic metre"),
    UT_F02("kelvin per kelvin"),
    UT_F03("kilopascal per bar"),
    UT_F04("millibar per bar"),
    UT_F05("megapascal per bar"),
    UT_F06("poise per bar"),
    UT_F07("pascal per bar"),
    UT_F08("milliampere per inch"),
    UT_F10("kelvin per hour"),
    UT_F11("kelvin per minute"),
    UT_F12("kelvin per second"),
    UT_F13("slug"),
    UT_F14("gram per kelvin"),
    UT_F15("kilogram per kelvin"),
    UT_F16("milligram per kelvin"),
    UT_F17("pound-force per foot"),
    UT_F18("kilogram square centimetre"),
    UT_F19("kilogram square millimetre"),
    UT_F20("pound inch squared"),
    UT_F21("pound-force inch"),
    UT_F22("pound-force foot per ampere"),
    UT_F23("gram per cubic decimetre"),
    UT_F24("kilogram per kilomol"),
    UT_F25("gram per hertz"),
    UT_F26("gram per day"),
    UT_F27("gram per hour"),
    UT_F28("gram per minute"),
    UT_F29("gram per second"),
    UT_F30("kilogram per day"),
    UT_F31("kilogram per minute"),
    UT_F32("milligram per day"),
    UT_F33("milligram per minute"),
    UT_F34("milligram per second"),
    UT_F35("gram per day kelvin"),
    UT_F36("gram per hour kelvin"),
    UT_F37("gram per minute kelvin"),
    UT_F38("gram per second kelvin"),
    UT_F39("kilogram per day kelvin"),
    UT_F40("kilogram per hour kelvin"),
    UT_F41("kilogram per minute kelvin"),
    UT_F42("kilogram per second kelvin"),
    UT_F43("milligram per day kelvin"),
    UT_F44("milligram per hour kelvin"),
    UT_F45("milligram per minute kelvin"),
    UT_F46("milligram per second kelvin"),
    UT_F47("newton per millimetre"),
    UT_F48("pound-force per inch"),
    UT_F49("rod [unit of distance]"),
    UT_F50("micrometre per kelvin"),
    UT_F51("centimetre per kelvin"),
    UT_F52("metre per kelvin"),
    UT_F53("millimetre per kelvin"),
    UT_F54("milliohm per metre"),
    UT_F55("ohm per mile (statute mile)"),
    UT_F56("ohm per kilometre"),
    UT_F57("milliampere per pound-force per square inch"),
    UT_F58("reciprocal bar"),
    UT_F59("milliampere per bar"),
    UT_F60("degree Celsius per bar"),
    UT_F61("kelvin per bar"),
    UT_F62("gram per day bar"),
    UT_F63("gram per hour bar"),
    UT_F64("gram per minute bar"),
    UT_F65("gram per second bar"),
    UT_F66("kilogram per day bar"),
    UT_F67("kilogram per hour bar"),
    UT_F68("kilogram per minute bar"),
    UT_F69("kilogram per second bar"),
    UT_F70("milligram per day bar"),
    UT_F71("milligram per hour bar"),
    UT_F72("milligram per minute bar"),
    UT_F73("milligram per second bar"),
    UT_F74("gram per bar"),
    UT_F75("milligram per bar"),
    UT_F76("milliampere per millimetre"),
    UT_F77("pascal second per kelvin"),
    UT_F78("inch of water"),
    UT_F79("inch of mercury"),
    UT_F80("water horse power"),
    UT_F81("bar per kelvin"),
    UT_F82("hectopascal per kelvin"),
    UT_F83("kilopascal per kelvin"),
    UT_F84("millibar per kelvin"),
    UT_F85("megapascal per kelvin"),
    UT_F86("poise per kelvin"),
    UT_F87("volt per litre minute"),
    UT_F88("newton centimetre"),
    UT_F89("newton metre per degree"),
    UT_F90("newton metre per ampere"),
    UT_F91("bar litre per second"),
    UT_F92("bar cubic metre per second"),
    UT_F93("hectopascal litre per second"),
    UT_F94("hectopascal cubic metre per second"),
    UT_F95("millibar litre per second"),
    UT_F96("millibar cubic metre per second"),
    UT_F97("megapascal litre per second"),
    UT_F98("megapascal cubic metre per second"),
    UT_F99("pascal litre per second"),
    UT_FAH("degree Fahrenheit"),
    UT_FAR("farad"),
    UT_FBM("fibre metre"),
    UT_FC("thousand cubic foot"),
    UT_FF("hundred cubic metre"),
    UT_FH("micromole"),
    UT_FIT("failures in time"),
    UT_FL("flake ton"),
    UT_FNU("Formazin nephelometric unit"),
    UT_FOT("foot"),
    UT_FP("pound per square foot"),
    UT_FR("foot per minute"),
    UT_FS("foot per second"),
    UT_FTK("square foot"),
    UT_FTQ("cubic foot"),
    UT_G01("pascal cubic metre per second"),
    UT_G04("centimetre per bar"),
    UT_G05("metre per bar"),
    UT_G06("millimetre per bar"),
    UT_G08("square inch per second"),
    UT_G09("square metre per second kelvin"),
    UT_G10("stokes per kelvin"),
    UT_G11("gram per cubic centimetre bar"),
    UT_G12("gram per cubic decimetre bar"),
    UT_G13("gram per litre bar"),
    UT_G14("gram per cubic metre bar"),
    UT_G15("gram per millilitre bar"),
    UT_G16("kilogram per cubic centimetre bar"),
    UT_G17("kilogram per litre bar"),
    UT_G18("kilogram per cubic metre bar"),
    UT_G19("newton metre per kilogram"),
    UT_G2("US gallon per minute"),
    UT_G20("pound-force foot per pound"),
    UT_G21("cup [unit of volume]"),
    UT_G23("peck"),
    UT_G24("tablespoon (US)"),
    UT_G25("teaspoon (US)"),
    UT_G26("stere"),
    UT_G27("cubic centimetre per kelvin"),
    UT_G28("litre per kelvin"),
    UT_G29("cubic metre per kelvin"),
    UT_G3("Imperial gallon per minute"),
    UT_G30("millilitre per kelvin"),
    UT_G31("kilogram per cubic centimetre"),
    UT_G32("ounce (avoirdupois) per cubic yard"),
    UT_G33("gram per cubic centimetre kelvin"),
    UT_G34("gram per cubic decimetre kelvin"),
    UT_G35("gram per litre kelvin"),
    UT_G36("gram per cubic metre kelvin"),
    UT_G37("gram per millilitre kelvin"),
    UT_G38("kilogram per cubic centimetre kelvin"),
    UT_G39("kilogram per litre kelvin"),
    UT_G40("kilogram per cubic metre kelvin"),
    UT_G41("square metre per second bar"),
    UT_G42("microsiemens per centimetre"),
    UT_G43("microsiemens per metre"),
    UT_G44("nanosiemens per centimetre"),
    UT_G45("nanosiemens per metre"),
    UT_G46("stokes per bar"),
    UT_G47("cubic centimetre per day"),
    UT_G48("cubic centimetre per hour"),
    UT_G49("cubic centimetre per minute"),
    UT_G50("gallon (US) per hour"),
    UT_G51("litre per second"),
    UT_G52("cubic metre per day"),
    UT_G53("cubic metre per minute"),
    UT_G54("millilitre per day"),
    UT_G55("millilitre per hour"),
    UT_G56("cubic inch per hour"),
    UT_G57("cubic inch per minute"),
    UT_G58("cubic inch per second"),
    UT_G59("milliampere per litre minute"),
    UT_G60("volt per bar"),
    UT_G61("cubic centimetre per day kelvin"),
    UT_G62("cubic centimetre per hour kelvin"),
    UT_G63("cubic centimetre per minute kelvin"),
    UT_G64("cubic centimetre per second kelvin"),
    UT_G65("litre per day kelvin"),
    UT_G66("litre per hour kelvin"),
    UT_G67("litre per minute kelvin"),
    UT_G68("litre per second kelvin"),
    UT_G69("cubic metre per day kelvin"),
    UT_G70("cubic metre per hour kelvin"),
    UT_G71("cubic metre per minute kelvin"),
    UT_G72("cubic metre per second kelvin"),
    UT_G73("millilitre per day kelvin"),
    UT_G74("millilitre per hour kelvin"),
    UT_G75("millilitre per minute kelvin"),
    UT_G76("millilitre per second kelvin"),
    UT_G77("millimetre to the fourth power"),
    UT_G78("cubic centimetre per day bar"),
    UT_G79("cubic centimetre per hour bar"),
    UT_G80("cubic centimetre per minute bar"),
    UT_G81("cubic centimetre per second bar"),
    UT_G82("litre per day bar"),
    UT_G83("litre per hour bar"),
    UT_G84("litre per minute bar"),
    UT_G85("litre per second bar"),
    UT_G86("cubic metre per day bar"),
    UT_G87("cubic metre per hour bar"),
    UT_G88("cubic metre per minute bar"),
    UT_G89("cubic metre per second bar"),
    UT_G90("millilitre per day bar"),
    UT_G91("millilitre per hour bar"),
    UT_G92("millilitre per minute bar"),
    UT_G93("millilitre per second bar"),
    UT_G94("cubic centimetre per bar"),
    UT_G95("litre per bar"),
    UT_G96("cubic metre per bar"),
    UT_G97("millilitre per bar"),
    UT_G98("microhenry per kiloohm"),
    UT_G99("microhenry per ohm"),
    UT_GB("gallon (US) per day"),
    UT_GBQ("gigabecquerel"),
    UT_GDW("gram, dry weight"),
    UT_GE("pound per gallon (US)"),
    UT_GF("gram per metre (gram per 100 centimetres)"),
    UT_GFI("gram of fissile isotope"),
    UT_GGR("great gross"),
    UT_GIA("gill (US)"),
    UT_GIC("gram, including container"),
    UT_GII("gill (UK)"),
    UT_GIP("gram, including inner packaging"),
    UT_GJ("gram per millilitre"),
    UT_GL("gram per litre"),
    UT_GLD("dry gallon (US)"),
    UT_GLI("gallon (UK)"),
    UT_GLL("gallon (US)"),
    UT_GM("gram per square metre"),
    UT_GO("milligram per square metre"),
    UT_GP("milligram per cubic metre"),
    UT_GQ("microgram per cubic metre"),
    UT_GRM("gram"),
    UT_GRN("grain"),
    UT_GRO("gross"),
    UT_GV("gigajoule"),
    UT_GWH("gigawatt hour"),
    UT_H03("henry per kiloohm"),
    UT_H04("henry per ohm"),
    UT_H05("millihenry per kiloohm"),
    UT_H06("millihenry per ohm"),
    UT_H07("pascal second per bar"),
    UT_H08("microbecquerel"),
    UT_H09("reciprocal year"),
    UT_H10("reciprocal hour"),
    UT_H11("reciprocal month"),
    UT_H12("degree Celsius per hour"),
    UT_H13("degree Celsius per minute"),
    UT_H14("degree Celsius per second"),
    UT_H15("square centimetre per gram"),
    UT_H16("square decametre"),
    UT_H18("square hectometre"),
    UT_H19("cubic hectometre"),
    UT_H20("cubic kilometre"),
    UT_H21("blank"),
    UT_H22("volt square inch per pound-force"),
    UT_H23("volt per inch"),
    UT_H24("volt per microsecond"),
    UT_H25("percent per kelvin"),
    UT_H26("ohm per metre"),
    UT_H27("degree per metre"),
    UT_H28("microfarad per kilometre"),
    UT_H29("microgram per litre"),
    UT_H30("square micrometre (square micron)"),
    UT_H31("ampere per kilogram"),
    UT_H32("ampere squared second"),
    UT_H33("farad per kilometre"),
    UT_H34("hertz metre"),
    UT_H35("kelvin metre per watt"),
    UT_H36("megaohm per kilometre"),
    UT_H37("megaohm per metre"),
    UT_H38("megaampere"),
    UT_H39("megahertz kilometre"),
    UT_H40("newton per ampere"),
    UT_H41("newton metre watt to the power minus 0,5"),
    UT_H42("pascal per metre"),
    UT_H43("siemens per centimetre"),
    UT_H44("teraohm"),
    UT_H45("volt second per metre"),
    UT_H46("volt per second"),
    UT_H47("watt per cubic metre"),
    UT_H48("attofarad"),
    UT_H49("centimetre per hour"),
    UT_H50("reciprocal cubic centimetre"),
    UT_H51("decibel per kilometre"),
    UT_H52("decibel per metre"),
    UT_H53("kilogram per bar"),
    UT_H54("kilogram per cubic decimetre kelvin"),
    UT_H55("kilogram per cubic decimetre bar"),
    UT_H56("kilogram per square metre second"),
    UT_H57("inch per two pi radiant"),
    UT_H58("metre per volt second"),
    UT_H59("square metre per newton"),
    UT_H60("cubic metre per cubic metre"),
    UT_H61("millisiemens per centimetre"),
    UT_H62("millivolt per minute"),
    UT_H63("milligram per square centimetre"),
    UT_H64("milligram per gram"),
    UT_H65("millilitre per cubic metre"),
    UT_H66("millimetre per year"),
    UT_H67("millimetre per hour"),
    UT_H68("millimole per gram"),
    UT_H69("picopascal per kilometre"),
    UT_H70("picosecond"),
    UT_H71("percent per month"),
    UT_H72("percent per hectobar"),
    UT_H73("percent per decakelvin"),
    UT_H74("watt per metre"),
    UT_H75("decapascal"),
    UT_H76("gram per millimetre"),
    UT_H77("module width"),
    UT_H79("French gauge"),
    UT_H80("rack unit"),
    UT_H81("millimetre per minute"),
    UT_H82("big point"),
    UT_H83("litre per kilogram"),
    UT_H84("gram millimetre"),
    UT_H85("reciprocal week"),
    UT_H87("piece"),
    UT_H88("megaohm kilometre"),
    UT_H89("percent per ohm"),
    UT_H90("percent per degree"),
    UT_H91("percent per ten thousand"),
    UT_H92("percent per one hundred thousand"),
    UT_H93("percent per hundred"),
    UT_H94("percent per thousand"),
    UT_H95("percent per volt"),
    UT_H96("percent per bar"),
    UT_H98("percent per inch"),
    UT_H99("percent per metre"),
    UT_HA("hank"),
    UT_HAD("Piece Day"),
    UT_HBA("hectobar"),
    UT_HBX("hundred boxes"),
    UT_HC("hundred count"),
    UT_HDW("hundred kilogram, dry weight"),
    UT_HEA("head"),
    UT_HGM("hectogram"),
    UT_HH("hundred cubic foot"),
    UT_HIU("hundred international unit"),
    UT_HKM("hundred kilogram, net mass"),
    UT_HLT("hectolitre"),
    UT_HM("mile per hour (statute mile)"),
    UT_HMO("Piece Month"),
    UT_HMQ("million cubic metre"),
    UT_HMT("hectometre"),
    UT_HPA("hectolitre of pure alcohol"),
    UT_HTZ("hertz"),
    UT_HUR("hour"),
    UT_HWE("Piece Week"),
    UT_IA("inch pound (pound inch)"),
    UT_IE("person"),
    UT_INH("inch"),
    UT_INK("square inch"),
    UT_INQ("cubic inch"),
    UT_ISD("international sugar degree"),
    UT_IU("inch per second"),
    UT_IUG("international unit per gram"),
    UT_IV("inch per second squared"),
    UT_J10("percent per millimetre"),
    UT_J12("per mille per psi"),
    UT_J13("degree API"),
    UT_J14("degree Baume (origin scale)"),
    UT_J15("degree Baume (US heavy)"),
    UT_J16("degree Baume (US light)"),
    UT_J17("degree Balling"),
    UT_J18("degree Brix"),
    UT_J19("degree Fahrenheit hour square foot per British thermal unit (thermochemical)"),
    UT_J2("joule per kilogram"),
    UT_J20("degree Fahrenheit per kelvin"),
    UT_J21("degree Fahrenheit per bar"),
    UT_J22("degree Fahrenheit hour square foot per British thermal unit (international table)"),
    UT_J23("degree Fahrenheit per hour"),
    UT_J24("degree Fahrenheit per minute"),
    UT_J25("degree Fahrenheit per second"),
    UT_J26("reciprocal degree Fahrenheit"),
    UT_J27("degree Oechsle"),
    UT_J28("degree Rankine per hour"),
    UT_J29("degree Rankine per minute"),
    UT_J30("degree Rankine per second"),
    UT_J31("degree Twaddell"),
    UT_J32("micropoise"),
    UT_J33("microgram per kilogram"),
    UT_J34("microgram per cubic metre kelvin"),
    UT_J35("microgram per cubic metre bar"),
    UT_J36("microlitre per litre"),
    UT_J38("baud"),
    UT_J39("British thermal unit (mean)"),
    UT_J40("British thermal unit (international table) foot per hour square foot degree Fahrenheit"),
    UT_J41("British thermal unit (international table) inch per hour square foot degree Fahrenheit"),
    UT_J42("British thermal unit (international table) inch per second square foot degree Fahrenheit"),
    UT_J43("British thermal unit (international table) per pound degree Fahrenheit"),
    UT_J44("British thermal unit (international table) per minute"),
    UT_J45("British thermal unit (international table) per second"),
    UT_J46("British thermal unit (thermochemical) foot per hour square foot degree Fahrenheit"),
    UT_J47("British thermal unit (thermochemical) per hour"),
    UT_J48("British thermal unit (thermochemical) inch per hour square foot degree Fahrenheit"),
    UT_J49("British thermal unit (thermochemical) inch per second square foot degree Fahrenheit"),
    UT_J50("British thermal unit (thermochemical) per pound degree Fahrenheit"),
    UT_J51("British thermal unit (thermochemical) per minute"),
    UT_J52("British thermal unit (thermochemical) per second"),
    UT_J53("coulomb square metre per kilogram"),
    UT_J54("megabaud"),
    UT_J55("watt second"),
    UT_J56("bar per bar"),
    UT_J57("barrel (UK petroleum)"),
    UT_J58("barrel (UK petroleum) per minute"),
    UT_J59("barrel (UK petroleum) per day"),
    UT_J60("barrel (UK petroleum) per hour"),
    UT_J61("barrel (UK petroleum) per second"),
    UT_J62("barrel (US petroleum) per hour"),
    UT_J63("barrel (US petroleum) per second"),
    UT_J64("bushel (UK) per day"),
    UT_J65("bushel (UK) per hour"),
    UT_J66("bushel (UK) per minute"),
    UT_J67("bushel (UK) per second"),
    UT_J68("bushel (US dry) per day"),
    UT_J69("bushel (US dry) per hour"),
    UT_J70("bushel (US dry) per minute"),
    UT_J71("bushel (US dry) per second"),
    UT_J72("centinewton metre"),
    UT_J73("centipoise per kelvin"),
    UT_J74("centipoise per bar"),
    UT_J75("calorie (mean)"),
    UT_J76("calorie (international table) per gram degree Celsius"),
    UT_J78("calorie (thermochemical) per centimetre second degree Celsius"),
    UT_J79("calorie (thermochemical) per gram degree Celsius"),
    UT_J81("calorie (thermochemical) per minute"),
    UT_J82("calorie (thermochemical) per second"),
    UT_J83("clo"),
    UT_J84("centimetre per second kelvin"),
    UT_J85("centimetre per second bar"),
    UT_J87("cubic centimetre per cubic metre"),
    UT_J90("cubic decimetre per day"),
    UT_J91("cubic decimetre per cubic metre"),
    UT_J92("cubic decimetre per minute"),
    UT_J93("cubic decimetre per second"),
    UT_J95("ounce (UK fluid) per day"),
    UT_J96("ounce (UK fluid) per hour"),
    UT_J97("ounce (UK fluid) per minute"),
    UT_J98("ounce (UK fluid) per second"),
    UT_J99("ounce (US fluid) per day"),
    UT_JE("joule per kelvin"),
    UT_JK("megajoule per kilogram"),
    UT_JM("megajoule per cubic metre"),
    UT_JNT("pipeline joint"),
    UT_JOU("joule"),
    UT_JPS("hundred metre"),
    UT_JWL("number of jewels"),
    UT_K1("kilowatt demand"),
    UT_K10("ounce (US fluid) per hour"),
    UT_K11("ounce (US fluid) per minute"),
    UT_K12("ounce (US fluid) per second"),
    UT_K13("foot per degree Fahrenheit"),
    UT_K14("foot per hour"),
    UT_K15("foot pound-force per hour"),
    UT_K16("foot pound-force per minute"),
    UT_K17("foot per psi"),
    UT_K18("foot per second degree Fahrenheit"),
    UT_K19("foot per second psi"),
    UT_K2("kilovolt ampere reactive demand"),
    UT_K20("reciprocal cubic foot"),
    UT_K21("cubic foot per degree Fahrenheit"),
    UT_K22("cubic foot per day"),
    UT_K23("cubic foot per psi"),
    UT_K26("gallon (UK) per day"),
    UT_K27("gallon (UK) per hour"),
    UT_K28("gallon (UK) per second"),
    UT_K3("kilovolt ampere reactive hour"),
    UT_K30("gallon (US liquid) per second"),
    UT_K31("gram-force per square centimetre"),
    UT_K32("gill (UK) per day"),
    UT_K33("gill (UK) per hour"),
    UT_K34("gill (UK) per minute"),
    UT_K35("gill (UK) per second"),
    UT_K36("gill (US) per day"),
    UT_K37("gill (US) per hour"),
    UT_K38("gill (US) per minute"),
    UT_K39("gill (US) per second"),
    UT_K40("standard acceleration of free fall"),
    UT_K41("grain per gallon (US)"),
    UT_K42("horsepower (boiler)"),
    UT_K43("horsepower (electric)"),
    UT_K45("inch per degree Fahrenheit"),
    UT_K46("inch per psi"),
    UT_K47("inch per second degree Fahrenheit"),
    UT_K48("inch per second psi"),
    UT_K49("reciprocal cubic inch"),
    UT_K50("kilobaud"),
    UT_K51("kilocalorie (mean)"),
    UT_K52("kilocalorie (international table) per hour metre degree Celsius"),
    UT_K53("kilocalorie (thermochemical)"),
    UT_K54("kilocalorie (thermochemical) per minute"),
    UT_K55("kilocalorie (thermochemical) per second"),
    UT_K58("kilomole per hour"),
    UT_K59("kilomole per cubic metre kelvin"),
    UT_K6("kilolitre"),
    UT_K60("kilomole per cubic metre bar"),
    UT_K61("kilomole per minute"),
    UT_K62("litre per litre"),
    UT_K63("reciprocal litre"),
    UT_K64("pound (avoirdupois) per degree Fahrenheit"),
    UT_K65("pound (avoirdupois) square foot"),
    UT_K66("pound (avoirdupois) per day"),
    UT_K67("pound per foot hour"),
    UT_K68("pound per foot second"),
    UT_K69("pound (avoirdupois) per cubic foot degree Fahrenheit"),
    UT_K70("pound (avoirdupois) per cubic foot psi"),
    UT_K71("pound (avoirdupois) per gallon (UK)"),
    UT_K73("pound (avoirdupois) per hour degree Fahrenheit"),
    UT_K74("pound (avoirdupois) per hour psi"),
    UT_K75("pound (avoirdupois) per cubic inch degree Fahrenheit"),
    UT_K76("pound (avoirdupois) per cubic inch psi"),
    UT_K77("pound (avoirdupois) per psi"),
    UT_K78("pound (avoirdupois) per minute"),
    UT_K79("pound (avoirdupois) per minute degree Fahrenheit"),
    UT_K80("pound (avoirdupois) per minute psi"),
    UT_K81("pound (avoirdupois) per second"),
    UT_K82("pound (avoirdupois) per second degree Fahrenheit"),
    UT_K83("pound (avoirdupois) per second psi"),
    UT_K84("pound per cubic yard"),
    UT_K85("pound-force per square foot"),
    UT_K86("pound-force per square inch degree Fahrenheit"),
    UT_K87("psi cubic inch per second"),
    UT_K88("psi litre per second"),
    UT_K89("psi cubic metre per second"),
    UT_K90("psi cubic yard per second"),
    UT_K91("pound-force second per square foot"),
    UT_K92("pound-force second per square inch"),
    UT_K93("reciprocal psi"),
    UT_K94("quart (UK liquid) per day"),
    UT_K95("quart (UK liquid) per hour"),
    UT_K96("quart (UK liquid) per minute"),
    UT_K97("quart (UK liquid) per second"),
    UT_K98("quart (US liquid) per day"),
    UT_K99("quart (US liquid) per hour"),
    UT_KA("cake"),
    UT_KAT("katal"),
    UT_KB("kilocharacter"),
    UT_KBA("kilobar"),
    UT_KCC("kilogram of choline chloride"),
    UT_KDW("kilogram drained net weight"),
    UT_KEL("kelvin"),
    UT_KGM("kilogram"),
    UT_KGS("kilogram per second"),
    UT_KHY("kilogram of hydrogen peroxide"),
    UT_KHZ("kilohertz"),
    UT_KI("kilogram per millimetre width"),
    UT_KIC("kilogram, including container"),
    UT_KIP("kilogram, including inner packaging"),
    UT_KJ("kilosegment"),
    UT_KJO("kilojoule"),
    UT_KL("kilogram per metre"),
    UT_KLK("lactic dry material percentage"),
    UT_KLX("kilolux"),
    UT_KMA("kilogram of methylamine"),
    UT_KMH("kilometre per hour"),
    UT_KMK("square kilometre"),
    UT_KMQ("kilogram per cubic metre"),
    UT_KMT("kilometre"),
    UT_KNI("kilogram of nitrogen"),
    UT_KNM("kilonewton per square metre"),
    UT_KNS("kilogram named substance"),
    UT_KNT("knot"),
    UT_KO("milliequivalence caustic potash per gram of product"),
    UT_KPA("kilopascal"),
    UT_KPH("kilogram of potassium hydroxide (caustic potash)"),
    UT_KPO("kilogram of potassium oxide"),
    UT_KPP("kilogram of phosphorus pentoxide (phosphoric anhydride)"),
    UT_KR("kiloroentgen"),
    UT_KSD("kilogram of substance 90 % dry"),
    UT_KSH("kilogram of sodium hydroxide (caustic soda)"),
    UT_KT("kit"),
    UT_KTN("kilotonne"),
    UT_KUR("kilogram of uranium"),
    UT_KVA("kilovolt - ampere"),
    UT_KVR("kilovar"),
    UT_KVT("kilovolt"),
    UT_KW("kilogram per millimetre"),
    UT_KWH("kilowatt hour"),
    UT_KWN("Kilowatt hour per normalized cubic metre"),
    UT_KWO("kilogram of tungsten trioxide"),
    UT_KWS("Kilowatt hour per standard cubic metre"),
    UT_KWT("kilowatt"),
    UT_KWY("kilowatt year"),
    UT_KX("millilitre per kilogram"),
    UT_L10("quart (US liquid) per minute"),
    UT_L11("quart (US liquid) per second"),
    UT_L12("metre per second kelvin"),
    UT_L13("metre per second bar"),
    UT_L14("square metre hour degree Celsius per kilocalorie (international table)"),
    UT_L15("millipascal second per kelvin"),
    UT_L16("millipascal second per bar"),
    UT_L17("milligram per cubic metre kelvin"),
    UT_L18("milligram per cubic metre bar"),
    UT_L19("millilitre per litre"),
    UT_L2("litre per minute"),
    UT_L20("reciprocal cubic millimetre"),
    UT_L21("cubic millimetre per cubic metre"),
    UT_L23("mole per hour"),
    UT_L24("mole per kilogram kelvin"),
    UT_L25("mole per kilogram bar"),
    UT_L26("mole per litre kelvin"),
    UT_L27("mole per litre bar"),
    UT_L28("mole per cubic metre kelvin"),
    UT_L29("mole per cubic metre bar"),
    UT_L30("mole per minute"),
    UT_L31("milliroentgen aequivalent men"),
    UT_L32("nanogram per kilogram"),
    UT_L33("ounce (avoirdupois) per day"),
    UT_L34("ounce (avoirdupois) per hour"),
    UT_L35("ounce (avoirdupois) per minute"),
    UT_L36("ounce (avoirdupois) per second"),
    UT_L37("ounce (avoirdupois) per gallon (UK)"),
    UT_L38("ounce (avoirdupois) per gallon (US)"),
    UT_L39("ounce (avoirdupois) per cubic inch"),
    UT_L40("ounce (avoirdupois)-force"),
    UT_L41("ounce (avoirdupois)-force inch"),
    UT_L42("picosiemens per metre"),
    UT_L43("peck (UK)"),
    UT_L44("peck (UK) per day"),
    UT_L45("peck (UK) per hour"),
    UT_L46("peck (UK) per minute"),
    UT_L47("peck (UK) per second"),
    UT_L48("peck (US dry) per day"),
    UT_L49("peck (US dry) per hour"),
    UT_L50("peck (US dry) per minute"),
    UT_L51("peck (US dry) per second"),
    UT_L52("psi per psi"),
    UT_L53("pint (UK) per day"),
    UT_L54("pint (UK) per hour"),
    UT_L55("pint (UK) per minute"),
    UT_L56("pint (UK) per second"),
    UT_L57("pint (US liquid) per day"),
    UT_L58("pint (US liquid) per hour"),
    UT_L59("pint (US liquid) per minute"),
    UT_L60("pint (US liquid) per second"),
    UT_L63("slug per day"),
    UT_L64("slug per foot second"),
    UT_L65("slug per cubic foot"),
    UT_L66("slug per hour"),
    UT_L67("slug per minute"),
    UT_L68("slug per second"),
    UT_L69("tonne per kelvin"),
    UT_L70("tonne per bar"),
    UT_L71("tonne per day"),
    UT_L72("tonne per day kelvin"),
    UT_L73("tonne per day bar"),
    UT_L74("tonne per hour kelvin"),
    UT_L75("tonne per hour bar"),
    UT_L76("tonne per cubic metre kelvin"),
    UT_L77("tonne per cubic metre bar"),
    UT_L78("tonne per minute"),
    UT_L79("tonne per minute kelvin"),
    UT_L80("tonne per minute bar"),
    UT_L81("tonne per second"),
    UT_L82("tonne per second kelvin"),
    UT_L83("tonne per second bar"),
    UT_L84("ton (UK shipping)"),
    UT_L85("ton long per day"),
    UT_L86("ton (US shipping)"),
    UT_L87("ton short per degree Fahrenheit"),
    UT_L88("ton short per day"),
    UT_L89("ton short per hour degree Fahrenheit"),
    UT_L90("ton short per hour psi"),
    UT_L91("ton short per psi"),
    UT_L92("ton (UK long) per cubic yard"),
    UT_L93("ton (US short) per cubic yard"),
    UT_L94("ton-force (US short)"),
    UT_L95("common year"),
    UT_L96("sidereal year"),
    UT_L98("yard per degree Fahrenheit"),
    UT_L99("yard per psi"),
    UT_LA("pound per cubic inch"),
    UT_LAC("lactose excess percentage"),
    UT_LBR("pound"),
    UT_LBT("troy pound (US)"),
    UT_LD("litre per day"),
    UT_LEF("leaf"),
    UT_LF("linear foot"),
    UT_LH("labour hour"),
    UT_LK("link"),
    UT_LM("linear metre"),
    UT_LN("length"),
    UT_LO("lot  [unit of procurement]"),
    UT_LP("liquid pound"),
    UT_LPA("litre of pure alcohol"),
    UT_LR("layer"),
    UT_LS("lump sum"),
    UT_LTN("ton (UK) or long ton (US)"),
    UT_LTR("litre"),
    UT_LUB("metric ton, lubricating oil"),
    UT_LUM("lumen"),
    UT_LUX("lux"),
    UT_LY("linear yard"),
    UT_M1("milligram per litre"),
    UT_M10("reciprocal cubic yard"),
    UT_M11("cubic yard per degree Fahrenheit"),
    UT_M12("cubic yard per day"),
    UT_M13("cubic yard per hour"),
    UT_M14("cubic yard per psi"),
    UT_M15("cubic yard per minute"),
    UT_M16("cubic yard per second"),
    UT_M17("kilohertz metre"),
    UT_M18("gigahertz metre"),
    UT_M19("Beaufort"),
    UT_M20("reciprocal megakelvin or megakelvin to the power minus one"),
    UT_M21("reciprocal kilovolt - ampere reciprocal hour"),
    UT_M22("millilitre per square centimetre minute"),
    UT_M23("newton per centimetre"),
    UT_M24("ohm kilometre"),
    UT_M25("percent per degree Celsius"),
    UT_M26("gigaohm per metre"),
    UT_M27("megahertz metre"),
    UT_M29("kilogram per kilogram"),
    UT_M30("reciprocal volt - ampere reciprocal second"),
    UT_M31("kilogram per kilometre"),
    UT_M32("pascal second per litre"),
    UT_M33("millimole per litre"),
    UT_M34("newton metre per square metre"),
    UT_M35("millivolt - ampere"),
    UT_M36("30-day month"),
    UT_M37("actual/360"),
    UT_M38("kilometre per second squared"),
    UT_M39("centimetre per second squared"),
    UT_M4("monetary value"),
    UT_M40("yard per second squared"),
    UT_M41("millimetre per second squared"),
    UT_M42("mile (statute mile) per second squared"),
    UT_M43("mil"),
    UT_M44("revolution"),
    UT_M45("degree [unit of angle] per second squared"),
    UT_M46("revolution per minute "),
    UT_M47("circular mil "),
    UT_M48("square mile (based on U.S. survey foot) "),
    UT_M49("chain (based on U.S. survey foot)"),
    UT_M5("microcurie"),
    UT_M50("furlong"),
    UT_M51("foot (U.S. survey) "),
    UT_M52("mile (based on U.S. survey foot) "),
    UT_M53("metre per pascal"),
    UT_M55("metre per radiant"),
    UT_M56("shake"),
    UT_M57("mile per minute "),
    UT_M58("mile per second "),
    UT_M59("metre per second pascal"),
    UT_M60("metre per hour"),
    UT_M61("inch per year"),
    UT_M62("kilometre per second "),
    UT_M63("inch per minute"),
    UT_M64("yard per second"),
    UT_M65("yard per minute"),
    UT_M66("yard per hour"),
    UT_M67("acre-foot (based on U.S. survey foot)"),
    UT_M68("cord (128 ft3)"),
    UT_M69("cubic mile (UK statute)"),
    UT_M7("micro-inch"),
    UT_M70("ton, register "),
    UT_M71("cubic metre per pascal"),
    UT_M72("bel"),
    UT_M73("kilogram per cubic metre pascal"),
    UT_M74("kilogram per pascal"),
    UT_M75("kilopound-force"),
    UT_M76("poundal"),
    UT_M77("kilogram metre per second squared"),
    UT_M78("pond"),
    UT_M79("square foot per hour "),
    UT_M80("stokes per pascal"),
    UT_M81("square centimetre per second"),
    UT_M82("square metre per second pascal"),
    UT_M83("denier "),
    UT_M84("pound per yard "),
    UT_M85("ton, assay"),
    UT_M86("pfund"),
    UT_M87("kilogram per second pascal"),
    UT_M88("tonne per month"),
    UT_M89("tonne per year"),
    UT_M9("million Btu per 1000 cubic foot"),
    UT_M90("kilopound per hour"),
    UT_M91("pound per pound"),
    UT_M92("pound-force foot"),
    UT_M93("newton metre per radian"),
    UT_M94("kilogram metre"),
    UT_M95("poundal foot"),
    UT_M96("poundal inch"),
    UT_M97("dyne metre"),
    UT_M98("kilogram centimetre per second"),
    UT_M99("gram centimetre per second"),
    UT_MAH("megavolt ampere reactive hour"),
    UT_MAL("megalitre"),
    UT_MAM("megametre"),
    UT_MAR("megavar"),
    UT_MAW("megawatt"),
    UT_MBE("thousand standard brick equivalent"),
    UT_MBF("thousand board foot"),
    UT_MBR("millibar"),
    UT_MC("microgram"),
    UT_MCU("millicurie"),
    UT_MD("air dry metric ton"),
    UT_MGM("milligram"),
    UT_MHZ("megahertz"),
    UT_MIK("square mile (statute mile)"),
    UT_MIL("thousand"),
    UT_MIN("minute [unit of time]"),
    UT_MIO("million"),
    UT_MIU("million international unit"),
    UT_MKD("Square Metre Day"),
    UT_MKM("Square Metre Month"),
    UT_MKW("Square Metre Week"),
    UT_MLD("milliard"),
    UT_MLT("millilitre"),
    UT_MMK("square millimetre"),
    UT_MMQ("cubic millimetre"),
    UT_MMT("millimetre"),
    UT_MND("kilogram, dry weight"),
    UT_MNJ("Mega Joule per Normalised cubic Metre"),
    UT_MON("month"),
    UT_MPA("megapascal"),
    UT_MQD("Cubic Metre Day"),
    UT_MQH("cubic metre per hour"),
    UT_MQM("Cubic Metre Month"),
    UT_MQS("cubic metre per second"),
    UT_MQW("Cubic Metre Week"),
    UT_MRD("Metre Day"),
    UT_MRM("Metre Month"),
    UT_MRW("Metre Week"),
    UT_MSK("metre per second squared"),
    UT_MTK("square metre"),
    UT_MTQ("cubic metre"),
    UT_MTR("metre"),
    UT_MTS("metre per second"),
    UT_MTZ("milihertz"),
    UT_MVA("megavolt - ampere"),
    UT_MWH("megawatt hour (1000 kW.h)"),
    UT_N1("pen calorie"),
    UT_N10("pound foot per second"),
    UT_N11("pound inch per second"),
    UT_N12("Pferdestaerke"),
    UT_N13("centimetre of mercury (0 ºC)"),
    UT_N14("centimetre of water (4 ºC)"),
    UT_N15("foot of water (39.2 ºF)"),
    UT_N16("inch of mercury (32 ºF)"),
    UT_N17("inch of mercury (60 ºF)"),
    UT_N18("inch of water (39.2 ºF)"),
    UT_N19("inch of water (60 ºF)"),
    UT_N20("kip per square inch"),
    UT_N21("poundal per square foot "),
    UT_N22("ounce (avoirdupois) per square inch "),
    UT_N23("conventional metre of water"),
    UT_N24("gram per square millimetre"),
    UT_N25("pound per square yard"),
    UT_N26("poundal per square inch"),
    UT_N27("foot to the fourth power "),
    UT_N28("cubic decimetre per kilogram"),
    UT_N29("cubic foot per pound"),
    UT_N3("print point"),
    UT_N30("cubic inch per pound"),
    UT_N31("kilonewton per metre"),
    UT_N32("poundal per inch"),
    UT_N33("pound-force per yard"),
    UT_N34("poundal second per square foot "),
    UT_N35("poise per pascal"),
    UT_N36("newton second per square metre"),
    UT_N37("kilogram per metre second"),
    UT_N38("kilogram per metre minute"),
    UT_N39("kilogram per metre day"),
    UT_N40("kilogram per metre hour"),
    UT_N41("gram per centimetre second"),
    UT_N42("poundal second per square inch"),
    UT_N43("pound per foot minute"),
    UT_N44("pound per foot day"),
    UT_N45("cubic metre per second pascal"),
    UT_N46("foot poundal"),
    UT_N47("inch poundal"),
    UT_N48("watt per square centimetre "),
    UT_N49("watt per square inch "),
    UT_N50("British thermal unit (international table) per square foot hour"),
    UT_N51("British thermal unit (thermochemical) per square foot hour"),
    UT_N52("British thermal unit (thermochemical) per square foot minute"),
    UT_N53("British thermal unit (international table) per square foot second"),
    UT_N54("British thermal unit (thermochemical) per square foot second"),
    UT_N55("British thermal unit (international table) per square inch second"),
    UT_N56("calorie (thermochemical) per square centimetre minute"),
    UT_N57("calorie (thermochemical) per square centimetre second"),
    UT_N58("British thermal unit (international table) per cubic foot "),
    UT_N59("British thermal unit (thermochemical) per cubic foot"),
    UT_N60("British thermal unit (international table) per degree Fahrenheit"),
    UT_N61("British thermal unit (thermochemical) per degree Fahrenheit"),
    UT_N62("British thermal unit (international table) per degree Rankine"),
    UT_N63("British thermal unit (thermochemical) per degree Rankine"),
    UT_N64("British thermal unit (thermochemical) per pound degree Rankine"),
    UT_N65("kilocalorie (international table) per gram kelvin"),
    UT_N66("British thermal unit (39 ºF) "),
    UT_N67("British thermal unit (59 ºF)"),
    UT_N68("British thermal unit (60 ºF) "),
    UT_N69("calorie (20 ºC) "),
    UT_N70("quad (1015 BtuIT)"),
    UT_N71("therm (EC)"),
    UT_N72("therm (U.S.)"),
    UT_N73("British thermal unit (thermochemical) per pound"),
    UT_N74("British thermal unit (international table) per hour square foot degree Fahrenheit"),
    UT_N75("British thermal unit (thermochemical) per hour square foot degree Fahrenheit"),
    UT_N76("British thermal unit (international table) per second square foot degree Fahrenheit"),
    UT_N77("British thermal unit (thermochemical) per second square foot degree Fahrenheit"),
    UT_N78("kilowatt per square metre kelvin"),
    UT_N79("kelvin per pascal"),
    UT_N80("watt per metre degree Celsius"),
    UT_N81("kilowatt per metre kelvin"),
    UT_N82("kilowatt per metre degree Celsius"),
    UT_N83("metre per degree Celcius metre"),
    UT_N84("degree Fahrenheit hour per British thermal unit (international table)"),
    UT_N85("degree Fahrenheit hour per British thermal unit (thermochemical)"),
    UT_N86("degree Fahrenheit second per British thermal unit (international table)"),
    UT_N87("degree Fahrenheit second per British thermal unit (thermochemical)"),
    UT_N88("degree Fahrenheit hour square foot per British thermal unit (international table) inch"),
    UT_N89("degree Fahrenheit hour square foot per British thermal unit (thermochemical) inch"),
    UT_N90("kilofarad"),
    UT_N91("reciprocal joule"),
    UT_N92("picosiemens"),
    UT_N93("ampere per pascal"),
    UT_N94("franklin"),
    UT_N95("ampere minute"),
    UT_N96("biot"),
    UT_N97("gilbert"),
    UT_N98("volt per pascal"),
    UT_N99("picovolt"),
    UT_NA("milligram per kilogram"),
    UT_NAR("number of articles"),
    UT_NCL("number of cells"),
    UT_NEW("newton"),
    UT_NF("message"),
    UT_NIL("nil"),
    UT_NIU("number of international units"),
    UT_NL("load"),
    UT_NM3("Normalised cubic metre"),
    UT_NMI("nautical mile"),
    UT_NMP("number of packs"),
    UT_NPT("number of parts"),
    UT_NT("net ton"),
    UT_NTU("Nephelometric turbidity unit"),
    UT_NU("newton metre"),
    UT_NX("part per thousand"),
    UT_OA("panel"),
    UT_ODE("ozone depletion equivalent"),
    UT_ODG("ODS Grams"),
    UT_ODK("ODS Kilograms"),
    UT_ODM("ODS Milligrams"),
    UT_OHM("ohm"),
    UT_ON("ounce per square yard"),
    UT_ONZ("ounce (avoirdupois)"),
    UT_OPM("oscillations per minute"),
    UT_OT("overtime hour"),
    UT_OZA("fluid ounce (US)"),
    UT_OZI("fluid ounce (UK)"),
    UT_P1("percent"),
    UT_P10("coulomb per metre"),
    UT_P11("kiloweber"),
    UT_P12("gamma"),
    UT_P13("kilotesla"),
    UT_P14("joule per second"),
    UT_P15("joule per minute"),
    UT_P16("joule per hour"),
    UT_P17("joule per day"),
    UT_P18("kilojoule per second"),
    UT_P19("kilojoule per minute"),
    UT_P2("pound per foot"),
    UT_P20("kilojoule per hour"),
    UT_P21("kilojoule per day"),
    UT_P22("nanoohm"),
    UT_P23("ohm circular-mil per foot "),
    UT_P24("kilohenry"),
    UT_P25("lumen per square foot "),
    UT_P26("phot"),
    UT_P27("footcandle"),
    UT_P28("candela per square inch "),
    UT_P29("footlambert"),
    UT_P30("lambert"),
    UT_P31("stilb"),
    UT_P32("candela per square foot"),
    UT_P33("kilocandela"),
    UT_P34("millicandela"),
    UT_P35("Hefner-Kerze"),
    UT_P36("international candle "),
    UT_P37("British thermal unit (international table) per square foot"),
    UT_P38("British thermal unit (thermochemical) per square foot"),
    UT_P39("calorie (thermochemical) per square centimetre "),
    UT_P40("langley"),
    UT_P41("decade (logarithmic)"),
    UT_P42("pascal squared second"),
    UT_P43("bel per metre"),
    UT_P44("pound mole"),
    UT_P45("pound mole per second"),
    UT_P46("pound mole per minute"),
    UT_P47("kilomole per kilogram"),
    UT_P48("pound mole per pound"),
    UT_P49("newton square metre per ampere"),
    UT_P5("five pack"),
    UT_P50("weber metre"),
    UT_P51("mol per kilogram pascal"),
    UT_P52("mol per cubic metre pascal"),
    UT_P53("unit pole "),
    UT_P54("milligray per second"),
    UT_P55("microgray per second"),
    UT_P56("nanogray per second"),
    UT_P57("gray per minute"),
    UT_P58("milligray per minute"),
    UT_P59("microgray per minute"),
    UT_P60("nanogray per minute"),
    UT_P61("gray per hour"),
    UT_P62("milligray per hour"),
    UT_P63("microgray per hour"),
    UT_P64("nanogray per hour"),
    UT_P65("sievert per second"),
    UT_P66("millisievert per second"),
    UT_P67("microsievert per second"),
    UT_P68("nanosievert per second"),
    UT_P69("rem per second"),
    UT_P70("sievert per hour"),
    UT_P71("millisievert per hour"),
    UT_P72("microsievert per hour"),
    UT_P73("nanosievert per hour"),
    UT_P74("sievert per minute"),
    UT_P75("millisievert per minute"),
    UT_P76("microsievert per minute"),
    UT_P77("nanosievert per minute"),
    UT_P78("reciprocal square inch"),
    UT_P79("pascal square metre per kilogram"),
    UT_P80("millipascal per metre"),
    UT_P81("kilopascal per metre"),
    UT_P82("hectopascal per metre"),
    UT_P83("standard atmosphere per metre"),
    UT_P84("technical atmosphere per metre"),
    UT_P85("torr per metre"),
    UT_P86("psi per inch"),
    UT_P87("cubic metre per second square metre"),
    UT_P88("rhe"),
    UT_P89("pound-force foot per inch"),
    UT_P90("pound-force inch per inch "),
    UT_P91("perm (0 ºC) "),
    UT_P92("perm (23 ºC) "),
    UT_P93("byte per second"),
    UT_P94("kilobyte per second"),
    UT_P95("megabyte per second"),
    UT_P96("reciprocal volt"),
    UT_P97("reciprocal radian"),
    UT_P98("pascal to the power sum of stoichiometric numbers"),
    UT_P99("mole per cubiv metre to the power sum of stoichiometric numbers"),
    UT_PAL("pascal"),
    UT_PD("pad"),
    UT_PFL("proof litre"),
    UT_PGL("proof gallon"),
    UT_PI("pitch"),
    UT_PLA("degree Plato"),
    UT_PO("pound per inch of length"),
    UT_PQ("page per inch"),
    UT_PR("pair"),
    UT_PS("pound-force per square inch"),
    UT_PTD("dry pint (US)"),
    UT_PTI("pint (UK)"),
    UT_PTL("liquid pint (US)"),
    UT_PTN("portion"),
    UT_Q10("joule per tesla"),
    UT_Q11("erlang"),
    UT_Q12("octet"),
    UT_Q13("octet per second"),
    UT_Q14("shannon"),
    UT_Q15("hartley"),
    UT_Q16("natural unit of information"),
    UT_Q17("shannon per second"),
    UT_Q18("hartley per second"),
    UT_Q19("natural unit of information per second"),
    UT_Q20("second per kilogramm"),
    UT_Q21("watt square metre"),
    UT_Q22("second per radian cubic metre"),
    UT_Q23("weber to the power minus one"),
    UT_Q24("reciprocal inch"),
    UT_Q25("dioptre"),
    UT_Q26("one per one"),
    UT_Q27("newton metre per metre"),
    UT_Q28("kilogram per square metre pascal second"),
    UT_Q29("microgram per hectogram"),
    UT_Q3("meal"),
    UT_Q30("pH (potential of Hydrogen)"),
    UT_Q31("kilojoule per gram"),
    UT_Q32("femtolitre"),
    UT_Q33("picolitre"),
    UT_Q34("nanolitre"),
    UT_Q35("megawatts per minute"),
    UT_Q36("square metre per cubic metre"),
    UT_Q37("Standard cubic metre per day"),
    UT_Q38("Standard cubic metre per hour"),
    UT_Q39("Normalized cubic metre per day"),
    UT_Q40("Normalized cubic metre per hour"),
    UT_Q41("Joule per normalised cubic metre"),
    UT_Q42("Joule per standard cubic metre"),
    UT_QA("page - facsimile"),
    UT_QAN("quarter (of a year)"),
    UT_QB("page - hardcopy"),
    UT_QR("quire"),
    UT_QTD("dry quart (US)"),
    UT_QTI("quart (UK)"),
    UT_QTL("liquid quart (US)"),
    UT_QTR("quarter (UK)"),
    UT_R1("pica"),
    UT_R9("thousand cubic metre"),
    UT_RH("running or operating hour"),
    UT_RM("ream"),
    UT_ROM("room"),
    UT_RP("pound per ream"),
    UT_RPM("revolutions per minute"),
    UT_RPS("revolutions per second"),
    UT_RT("revenue ton mile"),
    UT_S3("square foot per second"),
    UT_S4("square metre per second"),
    UT_SAN("half year (6 months)"),
    UT_SCO("score"),
    UT_SCR("scruple"),
    UT_SEC("second [unit of time]"),
    UT_SET("set"),
    UT_SG("segment"),
    UT_SIE("siemens"),
    UT_SM3("Standard cubic metre"),
    UT_SMI("mile (statute mile)"),
    UT_SQ("square"),
    UT_SQR("square, roofing"),
    UT_SR("strip"),
    UT_STC("stick"),
    UT_STI("stone (UK)"),
    UT_STK("stick, cigarette"),
    UT_STL("standard litre"),
    UT_STN("ton (US) or short ton (UK/US)"),
    UT_STW("straw"),
    UT_SW("skein"),
    UT_SX("shipment"),
    UT_SYR("syringe"),
    UT_T0("telecommunication line in service"),
    UT_T3("thousand piece"),
    UT_TAH("kiloampere hour (thousand ampere hour)"),
    UT_TAN("total acid number"),
    UT_TI("thousand square inch"),
    UT_TIC("metric ton, including container"),
    UT_TIP("metric ton, including inner packaging"),
    UT_TKM("tonne kilometre"),
    UT_TMS("kilogram of imported meat, less offal"),
    UT_TNE("tonne (metric ton)"),
    UT_TP("ten pack"),
    UT_TPI("teeth per inch"),
    UT_TPR("ten pair"),
    UT_TQD("thousand cubic metre per day"),
    UT_TRL("trillion (EUR)"),
    UT_TST("ten set"),
    UT_TTS("ten thousand sticks"),
    UT_U1("treatment"),
    UT_U2("tablet"),
    UT_UB("telecommunication line in service average"),
    UT_UC("telecommunication port"),
    UT_VA("volt - ampere per kilogram"),
    UT_VLT("volt"),
    UT_VP("percent volume"),
    UT_W2("wet kilo"),
    UT_WA("watt per kilogram"),
    UT_WB("wet pound"),
    UT_WCD("cord"),
    UT_WE("wet ton"),
    UT_WEB("weber"),
    UT_WEE("week"),
    UT_WG("wine gallon"),
    UT_WHR("watt hour"),
    UT_WM("working month"),
    UT_WSD("standard"),
    UT_WTT("watt"),
    UT_X1("Gunter's chain"),
    UT_YDK("square yard"),
    UT_YDQ("cubic yard"),
    UT_YRD("yard"),
    UT_Z11("hanging container"),
    UT_Z9("nanomole"),
    UT_ZP("page"),
    UT_ZZ("mutually defined"),
    UT_X1A("Drum, steel"),
    UT_X1B("Drum, aluminium"),
    UT_X1D("Drum, plywood"),
    UT_X1F("Container, flexible"),
    UT_X1G("Drum, fibre"),
    UT_X1W("Drum, wooden"),
    UT_X2C("Barrel, wooden"),
    UT_X3A("Jerrican, steel"),
    UT_X3H("Jerrican, plastic"),
    UT_X43("Bag, super bulk"),
    UT_X44("Bag, polybag"),
    UT_X4A("Box, steel"),
    UT_X4B("Box, aluminium"),
    UT_X4C("Box, natural wood"),
    UT_X4D("Box, plywood"),
    UT_X4F("Box, reconstituted wood"),
    UT_X4G("Box, fibreboard"),
    UT_X4H("Box, plastic"),
    UT_X5H("Bag, woven plastic"),
    UT_X5L("Bag, textile "),
    UT_X5M("Bag, paper "),
    UT_X6H("Composite packaging, plastic receptacle"),
    UT_X6P("Composite packaging, glass receptacle"),
    UT_X7A("Case, car"),
    UT_X7B("Case, wooden"),
    UT_X8A("Pallet, wooden"),
    UT_X8B("Crate, wooden"),
    UT_X8C("Bundle, wooden"),
    UT_XAA("Intermediate bulk container, rigid plastic"),
    UT_XAB("Receptacle, fibre "),
    UT_XAC("Receptacle, paper "),
    UT_XAD("Receptacle, wooden "),
    UT_XAE("Aerosol"),
    UT_XAF("Pallet, modular, collars 80cms * 60cms "),
    UT_XAG("Pallet, shrinkwrapped "),
    UT_XAH("Pallet, 100cms * 110cms "),
    UT_XAI("Clamshell"),
    UT_XAJ("Cone"),
    UT_XAL("Ball"),
    UT_XAM("Ampoule, non-protected "),
    UT_XAP("Ampoule, protected "),
    UT_XAT("Atomizer "),
    UT_XAV("Capsule"),
    UT_XB4("Belt"),
    UT_XBA("Barrel "),
    UT_XBB("Bobbin "),
    UT_XBC("Bottlecrate / bottlerack "),
    UT_XBD("Board"),
    UT_XBE("Bundle "),
    UT_XBF("Balloon, non-protected "),
    UT_XBG("Bag"),
    UT_XBH("Bunch"),
    UT_XBI("Bin"),
    UT_XBJ("Bucket "),
    UT_XBK("Basket "),
    UT_XBL("Bale, compressed "),
    UT_XBM("Basin"),
    UT_XBN("Bale, non-compressed "),
    UT_XBO("Bottle, non-protected, cylindrical "),
    UT_XBP("Balloon, protected "),
    UT_XBQ("Bottle, protected cylindrical"),
    UT_XBR("Bar"),
    UT_XBS("Bottle, non-protected, bulbous "),
    UT_XBT("Bolt "),
    UT_XBU("Butt "),
    UT_XBV("Bottle, protected bulbous"),
    UT_XBW("Box, for liquids"),
    UT_XBX("Box"),
    UT_XBY("Board, in bundle/bunch/truss "),
    UT_XBZ("Bars, in bundle/bunch/truss"),
    UT_XCA("Can, rectangular "),
    UT_XCB("Crate, beer"),
    UT_XCC("Churn"),
    UT_XCD("Can, with handle and spout "),
    UT_XCE("Creel"),
    UT_XCF("Coffer "),
    UT_XCG("Cage "),
    UT_XCH("Chest"),
    UT_XCI("Canister "),
    UT_XCJ("Coffin "),
    UT_XCK("Cask "),
    UT_XCL("Coil "),
    UT_XCM("Card"),
    UT_XCN("Container, not otherwise specified as transport equipment"),
    UT_XCO("Carboy, non-protected"),
    UT_XCP("Carboy, protected"),
    UT_XCQ("Cartridge"),
    UT_XCR("Crate"),
    UT_XCS("Case "),
    UT_XCT("Carton "),
    UT_XCU("Cup"),
    UT_XCV("Cover"),
    UT_XCW("Cage, roll "),
    UT_XCX("Can, cylindrical "),
    UT_XCY("Cylinder "),
    UT_XCZ("Canvas "),
    UT_XDA("Crate, multiple layer, plastic "),
    UT_XDB("Crate, multiple layer, wooden"),
    UT_XDC("Crate, multiple layer, cardboard "),
    UT_XDG("Cage, Commonwealth Handling Equipment Pool  (CHEP)"),
    UT_XDH("Box, Commonwealth Handling Equipment Pool (CHEP), Eurobox"),
    UT_XDI("Drum, iron "),
    UT_XDJ("Demijohn, non-protected"),
    UT_XDK("Crate, bulk, cardboard "),
    UT_XDL("Crate, bulk, plastic "),
    UT_XDM("Crate, bulk, wooden"),
    UT_XDN("Dispenser"),
    UT_XDP("Demijohn, protected"),
    UT_XDR("Drum "),
    UT_XDS("Tray, one layer no cover, plastic"),
    UT_XDT("Tray, one layer no cover, wooden "),
    UT_XDU("Tray, one layer no cover, polystyrene"),
    UT_XDV("Tray, one layer no cover, cardboard"),
    UT_XDW("Tray, two layers no cover, plastic tray"),
    UT_XDX("Tray, two layers no cover, wooden"),
    UT_XDY("Tray, two layers no cover, cardboard "),
    UT_XEC("Bag, plastic "),
    UT_XED("Case, with pallet base "),
    UT_XEE("Case, with pallet base, wooden "),
    UT_XEF("Case, with pallet base, cardboard"),
    UT_XEG("Case, with pallet base, plastic"),
    UT_XEH("Case, with pallet base, metal"),
    UT_XEI("Case, isothermic "),
    UT_XEN("Envelope "),
    UT_XFB("Flexibag"),
    UT_XFC("Crate, fruit "),
    UT_XFD("Crate, framed"),
    UT_XFE("Flexitank"),
    UT_XFI("Firkin "),
    UT_XFL("Flask"),
    UT_XFO("Footlocker "),
    UT_XFP("Filmpack "),
    UT_XFR("Frame"),
    UT_XFT("Foodtainer"),
    UT_XFW("Cart, flatbed"),
    UT_XFX("Bag, flexible container"),
    UT_XGB("Bottle, gas"),
    UT_XGI("Girder "),
    UT_XGL("Container, gallon"),
    UT_XGR("Receptacle, glass "),
    UT_XGU("Tray, containing horizontally stacked flat items"),
    UT_XGY("Bag, gunny"),
    UT_XGZ("Girders, in bundle/bunch/truss "),
    UT_XHA("Basket, with handle, plastic "),
    UT_XHB("Basket, with handle, wooden"),
    UT_XHC("Basket, with handle, cardboard "),
    UT_XHG("Hogshead "),
    UT_XHN("Hanger"),
    UT_XHR("Hamper "),
    UT_XIA("Package, display, wooden "),
    UT_XIB("Package, display, cardboard"),
    UT_XIC("Package, display, plastic"),
    UT_XID("Package, display, metal"),
    UT_XIE("Package, show"),
    UT_XIF("Package, flow "),
    UT_XIG("Package, paper wrapped"),
    UT_XIH("Drum, plastic"),
    UT_XIK("Package, cardboard, with bottle grip-holes "),
    UT_XIL("Tray, rigid, lidded stackable (CEN TS 14482:2002)"),
    UT_XIN("Ingot"),
    UT_XIZ("Ingots, in bundle/bunch/truss"),
    UT_XJB("Bag, jumbo"),
    UT_XJC("Jerrican, rectangular"),
    UT_XJG("Jug"),
    UT_XJR("Jar"),
    UT_XJT("Jutebag"),
    UT_XJY("Jerrican, cylindrical"),
    UT_XKG("Keg"),
    UT_XKI("Kit"),
    UT_XLE("Luggage"),
    UT_XLG("Log"),
    UT_XLT("Lot"),
    UT_XLU("Lug"),
    UT_XLV("Liftvan"),
    UT_XLZ("Logs, in bundle/bunch/truss"),
    UT_XMA("Crate, metal"),
    UT_XMB("Bag, multiply"),
    UT_XMC("Crate, milk"),
    UT_XME("Container, metal"),
    UT_XMR("Receptacle, metal "),
    UT_XMS("Sack, multi-wall "),
    UT_XMT("Mat"),
    UT_XMW("Receptacle, plastic wrapped "),
    UT_XMX("Matchbox "),
    UT_XNA("Not available"),
    UT_XNE("Unpacked or unpackaged "),
    UT_XNF("Unpacked or unpackaged, single unit"),
    UT_XNG("Unpacked or unpackaged, multiple units"),
    UT_XNS("Nest "),
    UT_XNT("Net"),
    UT_XNU("Net, tube, plastic "),
    UT_XNV("Net, tube, textile "),
    UT_XO1("Two sided cage on wheels with fixing strap"),
    UT_XO2("Trolley"),
    UT_XO3("Oneway pallet ISO 0 - 1/2 EURO Pallet"),
    UT_XO4("Oneway pallet ISO 1 - 1/1 EURO Pallet"),
    UT_XO5("Oneway pallet ISO 2 - 2/1 EURO Pallet"),
    UT_XO6("Pallet with exceptional dimensions"),
    UT_XO7("Wooden pallet  40 cm x 80 cm"),
    UT_XO8("Plastic pallet SRS 60 cm x 80 cm"),
    UT_XO9("Plastic pallet SRS 80 cm x 120 cm"),
    UT_XOA("Pallet, CHEP 40 cm x 60 cm"),
    UT_XOB("Pallet, CHEP 80 cm x 120 cm"),
    UT_XOC("Pallet, CHEP 100 cm x 120 cm"),
    UT_XOD("Pallet, AS 4068-1993"),
    UT_XOE("Pallet, ISO T11"),
    UT_XOF("Platform, unspecified weight or dimension"),
    UT_XOG("Pallet ISO 0 - 1/2 EURO Pallet"),
    UT_XOH("Pallet ISO 1 - 1/1 EURO Pallet"),
    UT_XOI("Pallet ISO 2 – 2/1 EURO Pallet"),
    UT_XOJ("1/4 EURO Pallet"),
    UT_XOK("Block"),
    UT_XOL("1/8 EURO Pallet"),
    UT_XOM("Synthetic pallet ISO 1"),
    UT_XON("Synthetic pallet ISO 2"),
    UT_XOP("Wholesaler pallet"),
    UT_XOQ("Pallet 80 X 100 cm"),
    UT_XOR("Pallet 60 X 100 cm"),
    UT_XOS("Oneway pallet"),
    UT_XOT("Octabin"),
    UT_XOU("Container, outer"),
    UT_XOV("Returnable pallet"),
    UT_XOW("Large bag, pallet sized"),
    UT_XOX("A wheeled pallet with raised rim (81 x 67 x 135)"),
    UT_XOY("A Wheeled pallet with raised rim (81 x 72 x 135)"),
    UT_XOZ("Wheeled pallet with raised rim ( 81 x 60 x 16)"),
    UT_XP1("CHEP pallet 60 cm x 80 cm "),
    UT_XP2("Pan"),
    UT_XP3("LPR pallet 60 cm x 80 cm"),
    UT_XP4("LPR pallet 80 cm x 120 cm"),
    UT_XPA("Packet "),
    UT_XPB("Pallet, box Combined open-ended box and pallet"),
    UT_XPC("Parcel "),
    UT_XPD("Pallet, modular, collars 80cms * 100cms "),
    UT_XPE("Pallet, modular, collars 80cms * 120cms "),
    UT_XPF("Pen "),
    UT_XPG("Plate"),
    UT_XPH("Pitcher"),
    UT_XPI("Pipe "),
    UT_XPJ("Punnet"),
    UT_XPK("Package"),
    UT_XPL("Pail "),
    UT_XPN("Plank"),
    UT_XPO("Pouch"),
    UT_XPP("Piece"),
    UT_XPR("Receptacle, plastic "),
    UT_XPT("Pot"),
    UT_XPU("Tray "),
    UT_XPV("Pipes, in bundle/bunch/truss "),
    UT_XPX("Pallet "),
    UT_XPY("Plates, in bundle/bunch/truss"),
    UT_XPZ("Planks, in bundle/bunch/truss"),
    UT_XQA("Drum, steel, non-removable head"),
    UT_XQB("Drum, steel, removable head"),
    UT_XQC("Drum, aluminium, non-removable head"),
    UT_XQD("Drum, aluminium, removable head"),
    UT_XQF("Drum, plastic, non-removable head"),
    UT_XQG("Drum, plastic, removable head"),
    UT_XQH("Barrel, wooden, bung type"),
    UT_XQJ("Barrel, wooden, removable head "),
    UT_XQK("Jerrican, steel, non-removable head"),
    UT_XQL("Jerrican, steel, removable head"),
    UT_XQM("Jerrican, plastic, non-removable head"),
    UT_XQN("Jerrican, plastic, removable head"),
    UT_XQP("Box, wooden, natural wood, ordinary"),
    UT_XQQ("Box, wooden, natural wood, with sift proof walls"),
    UT_XQR("Box, plastic, expanded "),
    UT_XQS("Box, plastic, solid"),
    UT_XRD("Rod"),
    UT_XRG("Ring "),
    UT_XRJ("Rack, clothing hanger"),
    UT_XRK("Rack "),
    UT_XRL("Reel "),
    UT_XRO("Roll "),
    UT_XRT("Rednet "),
    UT_XRZ("Rods, in bundle/bunch/truss"),
    UT_XSA("Sack "),
    UT_XSB("Slab"),
    UT_XSC("Crate, shallow "),
    UT_XSD("Spindle"),
    UT_XSE("Sea-chest"),
    UT_XSH("Sachet "),
    UT_XSI("Skid "),
    UT_XSK("Case, skeleton "),
    UT_XSL("Slipsheet "),
    UT_XSM("Sheetmetal "),
    UT_XSO("Spool "),
    UT_XSP("Sheet, plastic wrapping"),
    UT_XSS("Case, steel"),
    UT_XST("Sheet"),
    UT_XSU("Suitcase "),
    UT_XSV("Envelope, steel"),
    UT_XSW("Shrinkwrapped  "),
    UT_XSX("Set"),
    UT_XSY("Sleeve"),
    UT_XSZ("Sheets, in bundle/bunch/truss"),
    UT_XT1("Tablet"),
    UT_XTB("Tub"),
    UT_XTC("Tea-chest"),
    UT_XTD("Tube, collapsible"),
    UT_XTE("Tyre"),
    UT_XTG("Tank container, generic"),
    UT_XTI("Tierce"),
    UT_XTK("Tank, rectangular"),
    UT_XTL("Tub, with lid"),
    UT_XTN("Tin"),
    UT_XTO("Tun"),
    UT_XTR("Trunk"),
    UT_XTS("Truss"),
    UT_XTT("Bag, tote"),
    UT_XTU("Tube "),
    UT_XTV("Tube, with nozzle "),
    UT_XTW("Pallet, triwall"),
    UT_XTY("Tank, cylindrical"),
    UT_XTZ("Tubes, in bundle/bunch/truss "),
    UT_XUC("Uncaged "),
    UT_XUN("Unit"),
    UT_XVA("Vat"),
    UT_XVG("Bulk, gas (at 1031 mbar and 15°C)"),
    UT_XVI("Vial "),
    UT_XVK("Vanpack "),
    UT_XVL("Bulk, liquid "),
    UT_XVN("Vehicle"),
    UT_XVO("Bulk, solid, large particles (“nodules”) "),
    UT_XVP("Vacuum-packed"),
    UT_XVQ("Bulk, liquefied gas (at abnormal temperature/pressure) "),
    UT_XVR("Bulk, solid, granular particles (“grains”) "),
    UT_XVS("Bulk, scrap metal"),
    UT_XVY("Bulk, solid, fine particles (“powders”)"),
    UT_XWA("Intermediate bulk container"),
    UT_XWB("Wickerbottle "),
    UT_XWC("Intermediate bulk container, steel "),
    UT_XWD("Intermediate bulk container, aluminium "),
    UT_XWF("Intermediate bulk container, metal "),
    UT_XWG("Intermediate bulk container, steel, pressurised > 10 kpa"),
    UT_XWH("Intermediate bulk container, aluminium, pressurised > 10 kpa"),
    UT_XWJ("Intermediate bulk container, metal, pressure 10 kpa "),
    UT_XWK("Intermediate bulk container, steel, liquid "),
    UT_XWL("Intermediate bulk container, aluminium, liquid "),
    UT_XWM("Intermediate bulk container, metal, liquid "),
    UT_XWN("Intermediate bulk container, woven plastic, without coat/liner "),
    UT_XWP("Intermediate bulk container, woven plastic, coated "),
    UT_XWQ("Intermediate bulk container, woven plastic, with liner "),
    UT_XWR("Intermediate bulk container, woven plastic, coated and liner "),
    UT_XWS("Intermediate bulk container, plastic film"),
    UT_XWT("Intermediate bulk container, textile with out coat/liner "),
    UT_XWU("Intermediate bulk container, natural wood, with inner liner"),
    UT_XWV("Intermediate bulk container, textile, coated "),
    UT_XWW("Intermediate bulk container, textile, with liner "),
    UT_XWX("Intermediate bulk container, textile, coated and liner "),
    UT_XWY("Intermediate bulk container, plywood, with inner liner "),
    UT_XWZ("Intermediate bulk container, reconstituted wood, with inner liner"),
    UT_XXA("Bag, woven plastic, without inner coat/liner "),
    UT_XXB("Bag, woven plastic, sift proof "),
    UT_XXC("Bag, woven plastic, water resistant"),
    UT_XXD("Bag, plastics film "),
    UT_XXF("Bag, textile, without inner coat/liner "),
    UT_XXG("Bag, textile, sift proof "),
    UT_XXH("Bag, textile, water resistant"),
    UT_XXJ("Bag, paper, multi-wall "),
    UT_XXK("Bag, paper, multi-wall, water resistant"),
    UT_XYA("Composite packaging, plastic receptacle in steel drum"),
    UT_XYB("Composite packaging, plastic receptacle in steel crate box"),
    UT_XYC("Composite packaging, plastic receptacle in aluminium drum"),
    UT_XYD("Composite packaging, plastic receptacle in aluminium crate"),
    UT_XYF("Composite packaging, plastic receptacle in wooden box"),
    UT_XYG("Composite packaging, plastic receptacle in plywood drum"),
    UT_XYH("Composite packaging, plastic receptacle in plywood box "),
    UT_XYJ("Composite packaging, plastic receptacle in fibre drum"),
    UT_XYK("Composite packaging, plastic receptacle in fibreboard box"),
    UT_XYL("Composite packaging, plastic receptacle in plastic drum"),
    UT_XYM("Composite packaging, plastic receptacle in solid plastic box"),
    UT_XYN("Composite packaging, glass receptacle in steel drum"),
    UT_XYP("Composite packaging, glass receptacle in steel crate box"),
    UT_XYQ("Composite packaging, glass receptacle in aluminium drum"),
    UT_XYR("Composite packaging, glass receptacle in aluminium crate"),
    UT_XYS("Composite packaging, glass receptacle in wooden box"),
    UT_XYT("Composite packaging, glass receptacle in plywood drum"),
    UT_XYV("Composite packaging, glass receptacle in wickerwork hamper"),
    UT_XYW("Composite packaging, glass receptacle in fibre drum"),
    UT_XYX("Composite packaging, glass receptacle in fibreboard box "),
    UT_XYY("Composite packaging, glass receptacle in expandable plastic pack"),
    UT_XYZ("Composite packaging, glass receptacle in solid plastic pack"),
    UT_XZA("Intermediate bulk container, paper, multi-wall "),
    UT_XZB("Bag, large "),
    UT_XZC("Intermediate bulk container, paper, multi-wall, water resistant"),
    UT_XZD("Intermediate bulk container, rigid plastic, with structural equipment, solids"),
    UT_XZF("Intermediate bulk container, rigid plastic, freestanding, solids"),
    UT_XZG("Intermediate bulk container, rigid plastic, with structural equipment, pressurised"),
    UT_XZH("Intermediate bulk container, rigid plastic, freestanding, pressurised"),
    UT_XZJ("Intermediate bulk container, rigid plastic, with structural equipment, liquids "),
    UT_XZK("Intermediate bulk container, rigid plastic, freestanding, liquids"),
    UT_XZL("Intermediate bulk container, composite, rigid plastic, solids"),
    UT_XZM("Intermediate bulk container, composite, flexible plastic, solids"),
    UT_XZN("Intermediate bulk container, composite, rigid plastic, pressurised "),
    UT_XZP("Intermediate bulk container, composite, flexible plastic, pressurised"),
    UT_XZQ("Intermediate bulk container, composite, rigid plastic, liquids"),
    UT_XZR("Intermediate bulk container, composite, flexible plastic, liquids "),
    UT_XZS("Intermediate bulk container, composite"),
    UT_XZT("Intermediate bulk container, fibreboard"),
    UT_XZU("Intermediate bulk container, flexible"),
    UT_XZV("Intermediate bulk container, metal, other than steel"),
    UT_XZW("Intermediate bulk container, natural wood"),
    UT_XZX("Intermediate bulk container, plywood"),
    UT_XZY("Intermediate bulk container, reconstituted wood");

    public final String code, description;

    UnitType(String aName) {
        this.code = name().split("_")[1];
        this.description = aName;
    }
}
